import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Activity, Clock3, GitBranch, Plus, RefreshCw, Search, ShieldAlert } from "lucide-react";
import { useWorkflows } from "../../hooks/useWorkflows";

const control = "rounded-xl border border-stone-300 bg-white px-3 py-2 text-sm outline-none focus:border-[#a00028] focus:ring-2 focus:ring-[#a00028]/15";

export default function WorkflowsPage() {
  const { query, execute } = useWorkflows();
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [trigger, setTrigger] = useState("");
  const rows = useMemo(() => (query.data || []).filter((item) => (!search || `${item.name} ${item.description} ${item.assigned_agent}`.toLowerCase().includes(search.toLowerCase())) && (!status || item.status === status) && (!trigger || item.trigger_type === trigger)), [query.data, search, status, trigger]);
  const totalRuns = rows.reduce((sum, item) => sum + (item.executions || 0), 0);
  const success = totalRuns ? rows.reduce((sum, item) => sum + (item.executions || 0) * (item.success_rate || 0), 0) / totalRuns : null;
  const attention = rows.filter((item) => ["failed", "paused", "error"].includes(item.status)).length;
  return <main className="min-h-full bg-[#faf8f5] p-4 text-stone-900 md:p-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#a00028]">Automation</p><h1 className="mt-2 font-display text-4xl font-bold">Workflows</h1><p className="mt-2 text-stone-600">Design and govern repeatable AI-assisted delivery processes</p></div><div className="flex items-center gap-2"><span className="hidden text-xs text-stone-500 sm:inline">Last refreshed {query.dataUpdatedAt ? new Date(query.dataUpdatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—"}</span><button onClick={() => query.refetch()} aria-label="Refresh workflows" className="rounded-xl border border-stone-300 bg-white p-2.5"><RefreshCw size={17} className={query.isFetching ? "animate-spin" : ""} /></button><Link to="/workflows/new" className="inline-flex items-center gap-2 rounded-xl bg-[#a00028] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} />Create workflow</Link></div></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total workflows" value={query.data?.length || 0} detail="Authenticated catalogue" icon={GitBranch} /><Metric label="Published" value={rows.filter((item) => ["active", "published"].includes(item.status)).length} detail="Visible filtered workflows" icon={Activity} /><Metric label="Draft" value={rows.filter((item) => ["created", "draft"].includes(item.status)).length} detail="Visible editable definitions" icon={GitBranch} /><Metric label="Run success" value={success == null ? "—" : `${success.toFixed(1)}%`} detail={`${totalRuns} recorded runs`} icon={Activity} /><Metric label="Needs attention" value={attention} detail="Failed, paused, or error" icon={ShieldAlert} /></section>
    <section className="mt-6 grid gap-3 rounded-2xl border border-stone-300 bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-4"><label className="relative lg:col-span-2"><Search className="absolute left-3 top-3 text-stone-400" size={16} /><span className="sr-only">Search workflows</span><input className={`${control} w-full pl-9`} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search workflows, owners, or agents" /></label><select aria-label="Workflow status" className={control} value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{["draft", "active", "published", "paused", "failed"].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Workflow trigger" className={control} value={trigger} onChange={(event) => setTrigger(event.target.value)}><option value="">All triggers</option>{["MANUAL", "SCHEDULED", "DOMAIN_EVENT", "APPROVAL_COMPLETION"].map((item) => <option key={item}>{item}</option>)}</select></section>
    {query.isLoading ? <p className="mt-8 text-stone-600">Loading workflows…</p> : query.error ? <section role="alert" className="mt-8 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><h2 className="font-bold">Workflows could not be loaded</h2><button onClick={() => query.refetch()} className="mt-3 rounded-xl bg-[#a00028] px-4 py-2 text-white">Retry</button></section> : rows.length ? <><div className="mt-5 grid gap-3 md:hidden">{rows.map((workflow) => <WorkflowCard key={workflow.id} workflow={workflow} onRun={() => execute.mutate(workflow.id)} />)}</div><div className="mt-5 hidden overflow-x-auto rounded-2xl border border-stone-300 bg-white shadow-sm md:block"><table className="min-w-[1100px] w-full text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr>{["Workflow", "Category", "Status", "Version", "Trigger", "Steps", "Owner", "Last run", "Success", "Actions"].map((item) => <th className="p-3" key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((workflow) => <tr className="border-t border-stone-200 hover:bg-stone-50" key={workflow.id}><td className="p-3"><Link to={`/workflows/${workflow.id}/overview`} className="font-semibold text-[#a00028]">{workflow.name}</Link><p className="max-w-xs truncate text-xs text-stone-500">{workflow.description || "No description"}</p></td><td className="p-3">{workflow.definition?.metadata?.category || "Delivery governance"}</td><td className="p-3"><Status value={workflow.status} /></td><td className="p-3">v{workflow.current_version || 1}</td><td className="p-3">{workflow.trigger_type}</td><td className="p-3">{workflow.definition?.nodes?.length || 0}</td><td className="p-3">{workflow.definition?.metadata?.technical_owner || workflow.assigned_agent || "Unassigned"}</td><td className="p-3">{workflow.last_run_at ? new Date(workflow.last_run_at).toLocaleString() : "Never"}</td><td className="p-3">{workflow.success_rate == null ? "—" : `${workflow.success_rate}%`}</td><td className="p-3"><div className="flex gap-2"><Link to={`/workflows/${workflow.id}/overview`} className="text-[#a00028]">Open</Link><button disabled={!['active','published'].includes(workflow.status)} onClick={() => execute.mutate(workflow.id)} className="text-stone-700 disabled:opacity-40">Run</button></div></td></tr>)}</tbody></table></div></> : <section className="mt-8 rounded-2xl border border-dashed border-stone-300 bg-white p-8 text-center"><GitBranch className="mx-auto text-stone-400" /><h2 className="mt-3 font-bold">No workflows match this view</h2><p className="mt-1 text-stone-500">Create a governed draft or adjust the filters.</p></section>}
  </main>;
}
function Metric({ label, value, detail, icon: Icon }) { return <article className="rounded-2xl border border-stone-300 bg-white p-4 shadow-sm"><div className="flex justify-between"><p className="text-xs font-bold uppercase tracking-wide text-stone-500">{label}</p><Icon size={18} className="text-[#a00028]" /></div><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-stone-500">{detail}</p></article>; }
function Status({ value }) { const tone = ["active", "published"].includes(value) ? "border-emerald-200 bg-emerald-50 text-emerald-700" : value === "failed" ? "border-red-200 bg-red-50 text-red-700" : ["created", "draft"].includes(value) ? "border-amber-200 bg-amber-50 text-amber-800" : "border-stone-200 bg-stone-100 text-stone-700"; return <span className={`rounded-full border px-2.5 py-1 text-xs font-bold uppercase ${tone}`}>{value}</span>; }
function WorkflowCard({ workflow, onRun }) { return <article className="rounded-2xl border border-stone-300 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><Link to={`/workflows/${workflow.id}/overview`} className="font-semibold text-[#a00028]">{workflow.name}</Link><p className="mt-1 text-sm text-stone-500">{workflow.description}</p></div><Status value={workflow.status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-stone-500">Trigger</dt><dd>{workflow.trigger_type}</dd></div><div><dt className="text-stone-500">Steps</dt><dd>{workflow.definition?.nodes?.length || 0}</dd></div><div><dt className="text-stone-500">Success</dt><dd>{workflow.success_rate || 0}%</dd></div><div><dt className="text-stone-500">Duration</dt><dd>{workflow.average_duration_ms ? `${workflow.average_duration_ms} ms` : "—"}</dd></div></dl><button disabled={!['active','published'].includes(workflow.status)} onClick={onRun} className="mt-4 rounded-xl border border-stone-300 px-3 py-2 text-sm font-semibold disabled:opacity-40"><Clock3 size={15} className="mr-2 inline" />Run workflow</button></article>; }
