import { useDeferredValue } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Activity, Bot, Plus, RefreshCw, Search, ShieldAlert } from "lucide-react";
import { useAgents } from "../../hooks/useAgents";

const statuses = ["", "draft", "published", "enabled", "disabled", "archived", "error"];
const field = "rounded-xl border border-stone-300 bg-white px-3 py-2 text-sm text-stone-700 outline-none focus:border-[#a00028] focus:ring-2 focus:ring-[#a00028]/15";

export default function AgentsPage() {
  const [params, setParams] = useSearchParams();
  const search = useDeferredValue(params.get("search") || "");
  const filters = { search, status: params.get("status") || undefined, owner: params.get("owner") || undefined, model: params.get("model") || undefined, environment: params.get("environment") || undefined, include_archived: params.get("archived") === "true", sort: params.get("sort") || "updated_at", direction: params.get("direction") || "desc", page: Number(params.get("page") || 1), page_size: Number(params.get("page_size") || 10) };
  const query = useAgents(filters);
  const data = query.data || { items: [], total: 0, pages: 1, page: 1 };
  const update = (key, value) => setParams((current) => { const next = new URLSearchParams(current); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.set("page", "1"); return next; });
  const executions = data.items.reduce((sum, item) => sum + (item.execution_count || 0), 0);
  const success = executions ? data.items.reduce((sum, item) => sum + (item.execution_count || 0) * (item.success_rate || 0), 0) / executions : null;
  const attention = data.items.filter((item) => item.lifecycle_status === "error" || item.operational_health === "error" || (item.success_rate != null && item.success_rate < 80)).length;
  const canCreate = data.items[0]?.permissions?.create !== false;

  return <main className="min-h-full bg-[#faf8f5] p-4 text-stone-900 md:p-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#a00028]">Automation</p><h1 className="mt-2 font-display text-4xl font-bold">Agents</h1><p className="mt-2 text-stone-600">Build and govern specialized AI delivery agents</p></div><div className="flex items-center gap-2"><span className="hidden text-xs text-stone-500 sm:inline">Last refreshed {query.dataUpdatedAt ? new Date(query.dataUpdatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—"}</span><button aria-label="Refresh Agents" onClick={() => query.refetch()} className="rounded-xl border border-stone-300 bg-white p-2.5"><RefreshCw size={18} className={query.isFetching ? "animate-spin" : ""} /></button>{canCreate && <Link to="/agents/new" className="inline-flex items-center gap-2 rounded-xl bg-[#a00028] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} />Create agent</Link>}</div></header>

    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Agent portfolio summary">
      <Metric label="Total agents" value={data.total} detail="Accessible agents · current filter" icon={Bot} />
      <Metric label="Published" value={data.items.filter((item) => ["published", "enabled"].includes(item.lifecycle_status)).length} detail="Visible page · current filter" icon={Activity} />
      <Metric label="Drafts" value={data.items.filter((item) => item.lifecycle_status === "draft").length} detail="Visible page · editable versions" icon={Bot} />
      <Metric label="Success rate" value={success == null ? "—" : `${success.toFixed(1)}%`} detail={`${executions} executions · visible page`} icon={Activity} />
      <Metric label="Needs attention" value={attention} detail="Error state or success below 80%" icon={ShieldAlert} />
    </section>

    <section className="mt-6 grid gap-3 rounded-2xl border border-stone-300 bg-white p-4 shadow-sm sm:grid-cols-2 xl:grid-cols-7" aria-label="Agent directory filters">
      <label className="relative xl:col-span-2"><span className="sr-only">Search Agents</span><Search className="absolute left-3 top-3 text-stone-400" size={16} /><input aria-label="Search Agents" defaultValue={params.get("search") || ""} onChange={(event) => update("search", event.target.value)} className={`${field} w-full pl-9`} placeholder="Search name, slug, description" /></label>
      <Select label="Status" value={filters.status || ""} onChange={(value) => update("status", value)} options={statuses} />
      <input aria-label="Owner filter" value={filters.owner || ""} onChange={(event) => update("owner", event.target.value)} className={field} placeholder="Owner" />
      <input aria-label="Model filter" value={filters.model || ""} onChange={(event) => update("model", event.target.value)} className={field} placeholder="Model" />
      <Select label="Environment" value={filters.environment || ""} onChange={(value) => update("environment", value)} options={["", "development", "staging", "production"]} />
      <Select label="Sort" value={filters.sort} onChange={(value) => update("sort", value)} options={["updated_at", "name", "lifecycle", "owner"]} />
    </section>

    <DirectoryState query={query} filtered={Boolean(search || filters.status || filters.owner || filters.model || filters.environment)}>
      <div className="mt-5 grid gap-3 md:hidden">{data.items.map((agent) => <AgentCard key={agent.id} agent={agent} />)}</div>
      <div className="mt-5 hidden overflow-x-auto rounded-2xl border border-stone-300 bg-white shadow-sm md:block"><table className="min-w-[1120px] w-full text-left text-sm"><caption className="sr-only">Agent directory, {data.total} total results</caption><thead className="bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr>{["Agent", "Status", "Version", "Owner", "Model", "Tools", "Knowledge", "Last execution", "Success", "Updated"].map((value) => <th className="p-3" key={value}>{value}</th>)}</tr></thead><tbody>{data.items.map((agent) => <tr key={agent.id} className="border-t border-stone-200 hover:bg-stone-50"><td className="p-3"><Link className="font-semibold text-[#a00028] hover:underline" to={`/agents/${agent.id}/overview`}>{agent.name}</Link><small className="block max-w-xs truncate text-stone-500">{agent.description || agent.slug}</small></td><td className="p-3"><Status value={agent.lifecycle_status} /></td><td className="p-3">v{agent.published_version || agent.current_version}</td><td className="p-3">{agent.owner_id}</td><td className="p-3">{agent.model || "Not selected"}</td><td className="p-3">{agent.tool_count}</td><td className="p-3">{agent.knowledge_count}</td><td className="p-3">{agent.last_execution_at ? new Date(agent.last_execution_at).toLocaleString() : "Never"}</td><td className="p-3">{agent.success_rate == null ? "—" : `${agent.success_rate}%`}</td><td className="p-3 text-stone-500">{new Date(agent.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div>
    </DirectoryState>
    <nav className="mt-4 flex flex-wrap items-center justify-between gap-3" aria-label="Agent directory pagination"><span className="text-sm text-stone-500">{data.total} results · page {data.page} of {data.pages}</span><div className="flex gap-2"><button aria-label="Previous page" disabled={data.page <= 1} onClick={() => update("page", String(data.page - 1))} className="rounded-xl border border-stone-300 bg-white px-3 py-2 disabled:opacity-40">Previous</button><button aria-label="Next page" disabled={data.page >= data.pages} onClick={() => update("page", String(data.page + 1))} className="rounded-xl border border-stone-300 bg-white px-3 py-2 disabled:opacity-40">Next</button></div></nav>
  </main>;
}

function Metric({ label, value, detail, icon: Icon }) { return <article className="rounded-2xl border border-stone-300 bg-white p-4 shadow-sm"><div className="flex justify-between"><p className="text-xs font-bold uppercase tracking-wide text-stone-500">{label}</p><Icon size={18} className="text-[#a00028]" /></div><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-stone-500">{detail}</p></article>; }
function Status({ value }) { const tone = value === "enabled" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : value === "error" ? "border-red-200 bg-red-50 text-red-700" : value === "draft" ? "border-amber-200 bg-amber-50 text-amber-800" : "border-stone-200 bg-stone-100 text-stone-700"; return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold capitalize ${tone}`}>{value}</span>; }
function AgentCard({ agent }) { return <article className="rounded-2xl border border-stone-300 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><Link className="font-semibold text-[#a00028]" to={`/agents/${agent.id}/overview`}>{agent.name}</Link><p className="mt-1 text-sm text-stone-500">{agent.description || agent.slug}</p></div><Status value={agent.lifecycle_status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-stone-500">Model</dt><dd>{agent.model || "Not selected"}</dd></div><div><dt className="text-stone-500">Owner</dt><dd>{agent.owner_id}</dd></div><div><dt className="text-stone-500">Tools</dt><dd>{agent.tool_count}</dd></div><div><dt className="text-stone-500">Success</dt><dd>{agent.success_rate == null ? "—" : `${agent.success_rate}%`}</dd></div></dl></article>; }
function Select({ label, value, onChange, options }) { return <label className="text-xs font-semibold text-stone-500">{label}<select aria-label={`${label} filter`} value={value} onChange={(event) => onChange(event.target.value)} className={`${field} mt-1 w-full font-normal`}>{options.map((item) => <option key={item} value={item}>{item || "All"}</option>)}</select></label>; }
function DirectoryState({ query, filtered, children }) { if (query.isLoading) return <p aria-live="polite" className="mt-8 text-stone-600">Loading agents…</p>; if (query.error) { const status = query.error.response?.status; return <section role="alert" className="mt-8 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><h2 className="font-semibold">{status === 401 ? "Authentication required" : status === 403 ? "Permission denied" : status >= 500 ? "Server unavailable" : "Agents could not be loaded"}</h2><button onClick={() => query.refetch()} className="mt-3 rounded-xl bg-[#a00028] px-4 py-2 text-white">Retry</button></section>; } if (!query.data?.items?.length) return <section className="mt-8 rounded-2xl border border-dashed border-stone-300 bg-white p-8 text-center"><Bot className="mx-auto text-stone-400" /><h2 className="mt-3 font-semibold">{filtered ? "No agents match these filters" : "No agents yet"}</h2><p className="mt-1 text-stone-500">{filtered ? "Clear or adjust the directory filters." : "Create a governed agent to begin."}</p></section>; return children; }
