import {useState} from "react";
import {Search} from "lucide-react";
import {Button,Confidence,ConfigurationTemplate,FormField,KpiCard,PageHeader,StatePanel,StatusBadge,Surface,Tabs} from "../../components/design-system";
import {PageLoading,TableSkeleton} from "../../components/common/PageState";

const colors=["bg-[var(--axiom-brand-primary)]","bg-[var(--axiom-brand-orange)]","bg-[var(--axiom-brand-gold)]","bg-[var(--axiom-brand-charcoal)]","bg-[var(--axiom-status-success)]","bg-[var(--axiom-status-warning)]","bg-[var(--axiom-status-danger)]","bg-[var(--axiom-status-info)]"];
export default function DesignSystemPage(){const [enabled,setEnabled]=useState(true);return <ConfigurationTemplate header={<PageHeader eyebrow="Development only" title="Axiom Design System" description="Authoritative foundations, atomic components, responsive templates, and accessible interaction language."/>} navigation={<Tabs items={[{label:"Foundations",to:"#foundations",active:true},{label:"Components",to:"#components"},{label:"Templates",to:"#templates"}]}/>}><div className="grid gap-5">
  <Show title="Brand and colour tokens"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{colors.map(value=><div key={value}><div className={`h-16 ${value}`}/><p className="axiom-caption mt-1">Semantic token</p></div>)}</div></Show>
  <Show title="Typography, spacing, geometry, elevation, and motion"><div className="grid gap-5 md:grid-cols-2"><div><h1 className="font-display text-4xl font-bold">Display heading</h1><h2 className="mt-3 text-xl font-bold">Section title</h2><p className="mt-2 text-sm">Operational body text with a calm, compact hierarchy.</p><code className="mt-2 block text-xs">AX-CORRELATION-001</code></div><div className="grid grid-cols-3 gap-3"><Surface>Radius small</Surface><Surface accent>Accent surface</Surface><Surface className="shadow-[var(--axiom-shadow-raised)]">Raised</Surface></div></div></Show>
  <Show title="Buttons"><div className="flex flex-wrap gap-3"><Button>Primary</Button><Button variant="outline">Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="destructive">Danger</Button><Button variant="link">Link</Button><Button disabled>Disabled</Button><Button aria-busy>Loading…</Button></div></Show>
  <Show title="Inputs and forms"><div className="grid gap-4 md:grid-cols-2"><FormField id="showcase-search" label="Search" description="Labels stay visible."><label className="axiom-field flex items-center gap-2"><Search size={16}/><input id="showcase-search" className="min-w-0 flex-1 outline-none"/></label></FormField><FormField id="showcase-select" label="Status"><select id="showcase-select" className="axiom-field"><option>Active</option><option>Draft</option></select></FormField><FormField id="showcase-error" label="Invalid field" error="A valid value is required"><input id="showcase-error" aria-invalid aria-describedby="showcase-error-error" className="axiom-field"/></FormField><label className="flex items-center gap-3 text-sm font-semibold"><button role="switch" aria-checked={enabled} onClick={()=>setEnabled(!enabled)} className={`h-6 w-11 border p-0.5 ${enabled?"border-emerald-700 bg-emerald-100":"border-stone-400 bg-stone-100"}`}><span className={`block h-4 w-4 bg-current transition-transform ${enabled?"translate-x-5":""}`}/></button>Accessible toggle</label></div></Show>
  <Show title="Status, health, and confidence"><div className="flex flex-wrap gap-3">{["Draft","Pending","Active","Healthy","At risk","Critical","Failed","Blocked",undefined].map((x,i)=><StatusBadge key={i} value={x}/>)}<Confidence value="high"/><Confidence value="medium"/><Confidence value="low"/><Confidence value="insufficient"/></div></Show>
  <Show title="Cards and KPI grid"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><KpiCard label="On-time delivery" value="87%" detail="Source: delivery records" status="Healthy"/><KpiCard label="Open risks" value={14} status="At risk"/><KpiCard label="Evidence freshness" value="2d"/><KpiCard label="Unknown cost" value={null}/></div></Show>
  <Show title="Enterprise table"><div className="overflow-x-auto axiom-surface"><table className="axiom-table"><thead><tr><th>Entity</th><th>Status</th><th className="text-right">Value</th></tr></thead><tbody><tr><td>Enterprise Transformation</td><td><StatusBadge value="Active"/></td><td className="tabular-nums text-right">GBP 1,240,000</td></tr><tr><td>Evidence review</td><td><StatusBadge value="Unknown"/></td><td className="text-right">Unavailable</td></tr></tbody></table></div></Show>
  <Show title="Page states"><div className="grid gap-3 lg:grid-cols-3"><StatePanel title="No evidence" description="Connect an authorized source to begin."/><StatePanel kind="insufficient" title="Insufficient evidence" description="More observations are needed."/><StatePanel kind="error" title="Unable to load" description="Retry or quote AX-TEST-001 to support."/></div></Show>
  <Show title="Loading and templates"><PageLoading/><TableSkeleton rows={2}/><p className="axiom-caption mt-4">Dashboard, list, detail, workbench, configuration, wizard, designer, chat, administration, and empty-page templates share page gutters, headers, surfaces, states, and action rules.</p></Show>
</div></ConfigurationTemplate>}
function Show({title,children}:{title:string;children:React.ReactNode}){return <Surface><h2 className="font-display text-xl font-bold">{title}</h2><div className="mt-4">{children}</div></Surface>}
