import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { AlertTriangle, GitBranch, HeartPulse, RefreshCw, Target } from "lucide-react";
import AttentionRequiredPanel from "../../components/command-center/AttentionRequiredPanel";
import AIRecommendationsPanel from "../../components/command-center/AIRecommendationsPanel";
import DeliveryTrendChart from "../../components/command-center/DeliveryTrendChart";
import DetailDrawer from "../../components/command-center/DetailDrawer";
import MetricCard from "../../components/command-center/MetricCard";
import { EmptyState, ErrorState, PageSkeleton } from "../../components/command-center/CommandCenterStates";
import { useCommandCenter } from "../../hooks/useCommandCenter";
import useAuth from "../../hooks/useAuth";
import { isUsingMockDeliveryData } from "../../services/delivery-command-center.service";

const greeting = () => { const hour = new Date().getHours(); return hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"; };
export default function DashboardPage(){
  const navigate=useNavigate();
  const { user }=useAuth(); const [detail,setDetail]=useState(null); const [mode,setMode]=useState("review"); const [context,setContext]=useState(()=>globalThis.localStorage?.getItem("axiom.delivery.context")||"portfolio-all"); const query=useCommandCenter(context);
  if(query.isLoading)return <PageSkeleton/>; if(query.error)return <ErrorState onRetry={query.refetch}/>; const data=query.data;
  if(!data)return <EmptyState/>;
  const selectedContext=context==="portfolio-all"||data.contexts?.some(item=>item.id===context)?context:"portfolio-all";
  const metrics=[[data.portfolioHealth,HeartPulse],[data.sprintPredictability,Target],[data.openRisks,AlertTriangle],[data.dependencies,GitBranch]];
  const open=(item,nextMode="review")=>{if(item.route){navigate(item.route);return}setDetail(item);setMode(nextMode);};
  return <main className="min-h-full bg-[#faf8f5] p-5 text-[#1b1b1b] md:p-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#a00028]">Axiom Command Center</p><h1 className="font-display mt-2 text-3xl font-bold tracking-tight md:text-4xl">{greeting()}, {user?.givenName || user?.name?.split(" ")[0] || "there"}</h1><p className="mt-2 text-stone-600">Here’s what needs your attention today.</p></div><div className="flex flex-wrap items-center justify-end gap-3"><label className="text-xs font-semibold text-stone-600">Delivery context <select value={selectedContext} onChange={e=>{setContext(e.target.value);globalThis.localStorage?.setItem("axiom.delivery.context",e.target.value)}} className="ml-2 border border-stone-300 bg-white px-3 py-2 text-sm"><option value="portfolio-all">All delivery</option>{data.contexts?.map(c=><option key={c.id} value={c.id}>{c.name} · {c.type}</option>)}</select></label><span className="hidden text-xs text-stone-500 sm:block">Updated {new Date(data.generatedAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}{isUsingMockDeliveryData() ? " · Demo data" : ""}</span><button type="button" onClick={()=>query.refetch()} disabled={query.isFetching} className="inline-flex items-center gap-2 border border-stone-300 bg-white px-3.5 py-2.5 text-sm font-semibold text-stone-700 hover:bg-stone-50 focus:outline-none focus:ring-2 focus:ring-[#e0301e] disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${query.isFetching?"animate-spin":""}`}/>Refresh</button></div></header>
    <div className="mt-7 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([metric,icon])=><MetricCard key={metric.label} metric={metric} icon={icon}/>)}</div>
    <div className="mt-6 grid items-start gap-6 xl:grid-cols-3"><div className="space-y-6 xl:col-span-2"><DeliveryTrendChart data={data.deliveryTrend}/><AttentionRequiredPanel items={data.attentionItems} onSelect={open}/></div><AIRecommendationsPanel recommendations={data.recommendations} onReview={(r)=>open(r,"review")} onTakeAction={(r)=>open(r,"action")}/></div>
    <DetailDrawer open={!!detail} title={detail?.title || detail?.item || "Details"} onClose={()=>setDetail(null)}>{detail && <div className="mt-6 space-y-5"><p className="leading-7 text-slate-600">{detail.explanation || detail.description}</p>{detail.scoreBreakdown&&<section><h3 className="font-semibold">Why this needs attention</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{detail.scoreBreakdown.map(v=><li key={v}>{v}</li>)}</ul></section>}{detail.evidence&&<section><h3 className="font-semibold">Evidence</h3>{detail.evidence.map(e=><article key={e.id} className="mt-2 border border-slate-200 p-3 text-sm"><strong>{e.title}</strong><p className="mt-1 text-slate-600">{e.summary}</p><span className="mt-2 block text-xs text-slate-500">{e.sourceType} · {e.sourceRecordId}</span></article>)}</section>}{detail.owner && <dl className="grid grid-cols-2 gap-4 rounded-xl bg-slate-50 p-4 text-sm"><div><dt className="text-slate-500">Owner</dt><dd className="mt-1 font-semibold">{detail.owner}</dd></div><div><dt className="text-slate-500">Due date</dt><dd className="mt-1 font-semibold">{detail.dueDate}</dd></div></dl>}{mode==="action" && <div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><h3 className="font-semibold text-blue-950">Proposed action</h3><p className="mt-1 text-sm leading-6 text-blue-800">This will create a draft for approval. No external system will be updated.</p><button type="button" className="mt-4 rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2" onClick={()=>setMode("proposed")}>Create proposal</button></div>}{mode==="proposed" && <p role="status" className="rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-800">Proposed action created for review. No external action was executed.</p>}</div>}</DetailDrawer>
  </main>;
}
