import { NavLink } from "react-router-dom";
import { AlertTriangle, Bot, BookOpen, Boxes, CalendarCheck, CheckSquare, CircleGauge, Gauge, GitBranch, Layers3, ListChecks, ListTodo, MessageSquare, PanelLeftClose, PanelLeftOpen, PlugZap, Rocket, Settings, ShieldCheck, Sparkles, Target, Workflow, X } from "lucide-react";
import { productConfig } from "../../config/product";

const navigationGroups = [
  { label:"My Work", items:[{name:"My Day",path:"/my-day",icon:CalendarCheck},{name:"Command Center",path:"/command-center",icon:CircleGauge}] },
  { label:"Delivery", items:[{name:"Portfolio",path:"/portfolio",icon:Layers3},{name:"Sprints",path:"/sprints",icon:Target},{name:"Releases",path:"/releases",icon:Rocket},{name:"RAID",path:"/raid",icon:AlertTriangle},{name:"Dependencies",path:"/dependencies",icon:GitBranch},{name:"Actions",path:"/actions",icon:ListTodo}] },
  { label:"Intelligence", items:[{name:"Agile Performance",path:"/agile-performance",icon:Gauge},{name:"AI Copilot",path:"/copilot",icon:MessageSquare},{name:"Meetings",path:"/meetings",icon:Sparkles,end:true},{name:"Ceremonies",path:"/meetings/ceremonies",icon:ListChecks},{name:"Knowledge",path:"/knowledge",icon:BookOpen,end:true},{name:"Lessons Learned",path:"/knowledge/lessons",icon:BookOpen}] },
  { label:"Automation", items:[{name:"Agents",path:"/agents",icon:Bot},{name:"Workflows",path:"/workflows",icon:Workflow},{name:"Approvals",path:"/approvals",icon:CheckSquare}] },
  { label:"Administration", items:[{name:"Integrations",path:"/integrations",icon:PlugZap},{name:"Models",path:"/models",icon:Boxes},{name:"Governance",path:"/governance",icon:ShieldCheck},{name:"AI Operations",path:"/ai-operations",icon:Sparkles},{name:"Settings",path:"/settings",icon:Settings}] },
];
export default function Sidebar({collapsed,onCollapsedChange,onNavigate,mobile=false}) {
  return <aside aria-label="Primary navigation" className={`flex h-screen shrink-0 flex-col overflow-hidden border-r border-white/10 bg-[#202020] text-stone-300 transition-[width] duration-300 ${mobile||!collapsed?"w-64":"w-20"}`}>
    <div className={`flex shrink-0 items-center gap-3 border-b border-white/10 py-5 ${collapsed&&!mobile?"justify-center px-2":"px-5"}`}><div role="img" aria-label="Axiom monogram" className="relative flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden bg-[#a00028] font-display text-xl font-bold text-white after:absolute after:bottom-0 after:right-0 after:h-2 after:w-6 after:bg-[#ffb600]">A</div>{(!collapsed||mobile)&&<div className="min-w-0 flex-1"><h1 className="truncate text-base font-semibold text-white">{productConfig.shortName}</h1><p className="truncate text-xs text-stone-400">Delivery AI</p></div>}{mobile?<button type="button" aria-label="Close navigation" onClick={onNavigate} className="rounded-sm p-2 hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-[#ffb600]"><X className="h-5 w-5"/></button>:<button type="button" onClick={()=>onCollapsedChange(!collapsed)} aria-label={collapsed?"Expand sidebar":"Collapse sidebar"} aria-expanded={!collapsed} className="rounded-sm p-2 text-stone-400 hover:bg-white/10 hover:text-white focus:outline-none focus:ring-2 focus:ring-[#ffb600]">{collapsed?<PanelLeftOpen className="h-5 w-5"/>:<PanelLeftClose className="h-5 w-5"/>}</button>}</div>
    <nav className={`min-h-0 flex-1 overflow-y-auto py-4 ${collapsed&&!mobile?"px-2":"px-3"}`}>{navigationGroups.map(group=><div key={group.label} className="mb-5">{(!collapsed||mobile)&&<h2 className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.18em] text-stone-500">{group.label}</h2>}<div className="space-y-1">{group.items.map(item=>{const Icon=item.icon;return <NavLink end={item.end} key={item.path} to={item.path} onClick={onNavigate} title={collapsed&&!mobile?item.name:undefined} className={({isActive})=>`relative flex items-center rounded-sm py-2.5 text-sm font-medium transition focus:outline-none focus:ring-2 focus:ring-[#ffb600] ${collapsed&&!mobile?"justify-center px-2":"gap-3 px-3"} ${isActive?"bg-white/10 text-white before:absolute before:inset-y-1 before:left-0 before:w-1 before:bg-[#e65b19]":"text-stone-400 hover:bg-white/[0.06] hover:text-white"}`}><Icon className="h-[18px] w-[18px] shrink-0"/>{(!collapsed||mobile)&&<span>{item.name}</span>}</NavLink>})}</div></div>)}</nav>
  </aside>;
}
