const providerModels={openai:["gpt-4.1","gpt-4.1-mini"],bedrock:["amazon.nova-lite-v1:0","anthropic.claude-3-5-sonnet-20241022-v2:0"]};
export default function ChatHeader({agents,agentId,setAgentId,provider,setProvider,model,setModel,workspace,setWorkspace,runtime}){
 const agent=agents.find(item=>item.id===agentId);const controlled=Boolean(agent);const authoritativeProvider=agent?.model_provider||agent?.model_configuration?.provider;const authoritativeModel=agent?.model||agent?.model_configuration?.model;
 const selectClass="mt-1 block max-w-52 border border-stone-300 bg-[#202020] px-3 py-2 text-xs normal-case text-stone-100";
 return <header className="flex flex-wrap items-center gap-3 border-b border-stone-300 bg-white px-4 py-3 text-stone-900"><div className="mr-auto min-w-64"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#a00028]">Evidence-led delivery</p><h1 className="font-display text-xl font-bold">Axiom AI Delivery Copilot</h1><p className="text-xs text-stone-500">Ask, investigate, and prepare controlled actions</p></div>
 {[['Workspace',workspace,setWorkspace,['Delivery Management','Engineering','Portfolio Office']],['Agent',agentId,setAgentId,[{value:'',label:'Delivery Copilot · Auto'},...agents.map(item=>({value:item.id,label:`${item.name} · ${item.lifecycle_status} · ${item.operational_health}`}))]]].map(([label,value,setValue,options])=><label key={label} className="text-[10px] uppercase tracking-wide text-stone-500">{label}<select aria-label={label} value={value} onChange={e=>setValue(e.target.value)} className={selectClass}>{options.map(option=>typeof option==='string'?<option key={option}>{option}</option>:<option key={option.value} value={option.value}>{option.label}</option>)}</select></label>)}
 <label className="text-[10px] uppercase tracking-wide text-stone-500">Provider<select aria-label="Provider" disabled={controlled} value={controlled?authoritativeProvider||provider:provider} onChange={e=>{setProvider(e.target.value);setModel(e.target.value==="automatic"?"automatic":providerModels[e.target.value][0])}} className={`${selectClass} disabled:opacity-60`}><option value="automatic">Automatic</option><option value="openai">OpenAI</option><option value="bedrock">AWS Bedrock</option></select></label>
 <label className="text-[10px] uppercase tracking-wide text-stone-500">Model<select aria-label="Model" disabled={controlled||provider==="automatic"} value={controlled?authoritativeModel||model:model} onChange={e=>setModel(e.target.value)} className={`${selectClass} disabled:opacity-60`}>{controlled?<option>{authoritativeModel}</option>:provider==="automatic"?<option value="automatic">Automatic</option>:providerModels[provider].map(item=><option key={item}>{item}</option>)}</select></label>
 {runtime?.selectedAgent&&<div className="border border-[#a00028]/20 bg-[#a00028]/5 px-3 py-2 text-[11px] text-[#a00028]"><span className="block font-medium">Executing: {runtime.selectedAgent.name}</span><span>{runtime.selectedAgent.provider} · {runtime.selectedAgent.model}</span></div>}
 <div className="border border-emerald-700/20 bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-800">● Runtime online</div></header>;
}
