import {useEffect,useRef,useState} from "react";
import {CircleHelp} from "lucide-react";
import DynamicFieldRenderer from "./DynamicFieldRenderer";

export default function RequiredInformationCard({request,onSubmit,onCancel}){
  const [values,setValues]=useState(request?.known_values||{});const [submitting,setSubmitting]=useState(false);const [errors,setErrors]=useState({});const [submissionError,setSubmissionError]=useState("");const headingRef=useRef(null);
  useEffect(()=>headingRef.current?.focus(),[request?.continuation_id]);
  if(!request)return null;
  const feedback=request.validation_feedback||{};const serverErrors={};for(const name of feedback.invalid_fields||[])serverErrors[name]="Enter a valid value for this field.";for(const name of feedback.unresolved_fields||[])serverErrors[name]="This value is still required.";const visibleErrors={...serverErrors,...errors};const visibleSubmissionError=submissionError||(feedback.warnings||[]).join(" ");
  async function submit(e){e.preventDefault();const next={};for(const field of request.fields||[])if(field.required&&(values[field.name]===undefined||values[field.name]===""||values[field.name]===null||(Array.isArray(values[field.name])&&!values[field.name].length)))next[field.name]=`${field.label} is required.`;setErrors(next);if(Object.keys(next).length)return;setSubmitting(true);setSubmissionError("");try{await onSubmit(values)}catch(error){setSubmissionError(error instanceof Error?error.message:"Unable to submit runtime details.")}finally{setSubmitting(false)}}
  return <form noValidate className="rounded-sm border border-[#d9d5d2] border-l-4 border-l-[#b0002a] bg-white p-5 text-[#201d1b] shadow-sm" onSubmit={submit} aria-labelledby="required-information-title">
    <div className="flex items-center gap-3"><span className="rounded-sm bg-[#f7ecef] p-2 text-[#b0002a]"><CircleHelp size={18}/></span><div><h3 id="required-information-title" ref={headingRef} tabIndex={-1} className="font-semibold text-[#201d1b]">{request.title||"Additional Information Required"}</h3><p className="text-xs text-[#6f6965]">{request.description||"Execution is paused and will resume with the same runtime ID."}</p></div></div>
    {Object.keys(visibleErrors).length>0&&<p role="alert" className="mt-3 border-l-4 border-[#b0002a] bg-[#fff1f3] p-3 text-sm text-[#8f0023]">Complete the marked required fields.</p>}
    {visibleSubmissionError&&<p role="alert" className="mt-3 border-l-4 border-[#b0002a] bg-[#fff1f3] p-3 text-sm text-[#8f0023]">{visibleSubmissionError}</p>}
    <div className="mt-4 grid gap-4 md:grid-cols-2">{(request.fields||[]).map(field=><label className="text-sm font-medium text-[#423d39]" key={field.name}>{field.label}{field.required&&<span className="text-[#b0002a]"> *</span>}<DynamicFieldRenderer field={field} value={values[field.name]} invalid={Boolean(visibleErrors[field.name])} onChange={value=>{setValues(current=>({...current,[field.name]:value}));setErrors(current=>({...current,[field.name]:undefined}))}}/>{visibleErrors[field.name]&&<span className="mt-1 block text-xs text-[#b0002a]">{visibleErrors[field.name]}</span>}</label>)}</div>
    <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-sm border border-[#bdb7b2] bg-white px-4 py-2 text-sm font-medium text-[#423d39] hover:bg-[#f7f5f3]">Cancel execution</button><button disabled={submitting} className="rounded-sm bg-[#b0002a] px-4 py-2 text-sm font-semibold text-white hover:bg-[#8f0023] disabled:cursor-not-allowed disabled:opacity-60">{submitting?"Submitting…":"Submit details"}</button></div>
  </form>
}
