import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";
import RAIDPage from "./RAIDPage";

const items=[
  {id:"risk-1",reference:"R-031",name:"Payment API delay",description:"Fictional provider capacity constraint",itemType:"RISK",status:"OPEN",projectId:"project-1",probability:"ALMOST_CERTAIN",impact:"CRITICAL",exposureScore:25,exposureBand:"CRITICAL",residualExposureBand:"CRITICAL",attentionScore:80,attentionReasons:["Critical exposure +40"],ownerId:"owner-1",reviewDate:"2026-08-18",identifiedAt:"2026-08-01T00:00:00Z",ageDays:13,evidenceCount:1,version:1},
  {id:"issue-1",reference:"I-011",name:"SIT instability",description:"Fictional test failures",itemType:"ISSUE",status:"INVESTIGATING",projectId:"project-1",severity:"CRITICAL",attentionScore:45,attentionReasons:[],ownerId:"owner-2",dueDate:"2026-08-16",identifiedAt:"2026-08-10T00:00:00Z",ageDays:4,evidenceCount:1,version:1},
];
const mocks=vi.hoisted(()=>({getRAIDItems:vi.fn(),getRAIDSummary:vi.fn(),getRAIDHeatmap:vi.fn(),getRAIDCandidates:vi.fn(),getRAIDHygiene:vi.fn(),getRAIDDetail:vi.fn(),createRAIDItem:vi.fn(),reviewRAIDItem:vi.fn(),transitionRAIDItem:vi.fn(),createRAIDProposal:vi.fn(),acceptRAIDCandidate:vi.fn(),dismissRAIDCandidate:vi.fn()}));
vi.mock("../../services/raid.service",()=>mocks);
function setup(path="/raid"){return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/raid" element={<RAIDPage/>}/><Route path="/raid/:raidId" element={<RAIDPage/>}/></Routes></MemoryRouter>)}
beforeEach(()=>{Object.values(mocks).forEach(mock=>mock.mockReset());mocks.getRAIDItems.mockImplementation(async filters=>({items:items.filter(item=>!filters.type||item.itemType===filters.type),page:1,pageSize:20,total:filters.type?items.filter(item=>item.itemType===filters.type).length:2,pages:1,traceId:"trace",generatedAt:"2026-08-14T10:00:00Z",source:"persisted"}));mocks.getRAIDSummary.mockResolvedValue({criticalRisks:1,openIssues:1,atRiskDependencies:0,pendingDecisions:0,overdueActions:0,unvalidatedAssumptions:0,generatedAt:"2026-08-14T10:00:00Z"});mocks.getRAIDHeatmap.mockResolvedValue({cells:[{probability:"ALMOST_CERTAIN",impact:"CRITICAL",score:25,band:"CRITICAL",count:1,itemIds:["risk-1"]}],totalRisks:1,generatedAt:"2026-08-14T10:00:00Z"});mocks.getRAIDCandidates.mockResolvedValue({items:[]});mocks.getRAIDHygiene.mockResolvedValue({items:[],total:0,generatedAt:"2026-08-14T10:00:00Z"});mocks.getRAIDDetail.mockResolvedValue({item:items[0],evidence:[{id:"ev-1",title:"Provider status",summary:"Capacity constrained",sourceType:"STATUS_UPDATE",sourceSystem:"MANUAL",capturedAt:"2026-08-14T09:00:00Z"}],relationships:[],recommendations:[],proposals:[],reviews:[],history:[{id:"h-1",eventType:"CREATED",actorId:"owner-1",changedAt:"2026-08-14T09:00:00Z"}],traceId:"trace",source:"persisted",externalWrites:false});});

describe("RAID intelligence",()=>{
  it("loads persisted summary, filters all six type tabs, and opens URL-addressable details",async()=>{setup();expect((await screen.findAllByText("R-031"))[0]).toBeInTheDocument();expect(screen.getByRole("button",{name:/Critical risks: 1/})).toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"Issues"}));await waitFor(()=>expect(screen.queryAllByText("R-031")).toHaveLength(0));expect(screen.getAllByText("I-011")[0]).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Review I-011"}));await waitFor(()=>expect(mocks.getRAIDDetail).toHaveBeenCalledWith("issue-1",expect.any(AbortSignal)));expect(await screen.findByRole("dialog",{name:/R-031/})).toBeInTheDocument();});
  it("filters the register from an accessible heatmap cell",async()=>{setup();const cell=await screen.findByRole("gridcell",{name:/ALMOST CERTAIN probability, CRITICAL impact/});fireEvent.click(cell);await waitFor(()=>expect(mocks.getRAIDItems).toHaveBeenLastCalledWith(expect.objectContaining({type:"RISK",exposure_band:"CRITICAL"}),expect.any(AbortSignal)));expect(screen.getByRole("status")).toHaveTextContent("Register filtered to critical risks");});
  it("shows partial-data state and retries a failed persisted register",async()=>{mocks.getRAIDItems.mockRejectedValueOnce(new Error("offline"));setup();expect(await screen.findByRole("alert")).toHaveTextContent("could not be loaded");expect(screen.getByText(/Some intelligence panels/)).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Retry"}));expect((await screen.findAllByText("R-031"))[0]).toBeInTheDocument();});
  it("treats omitted optional API collections as empty arrays",async()=>{mocks.getRAIDItems.mockResolvedValueOnce({page:1,pageSize:20,total:0,pages:1,generatedAt:"2026-08-14T10:00:00Z",source:"persisted"});mocks.getRAIDHeatmap.mockResolvedValueOnce({});mocks.getRAIDCandidates.mockResolvedValueOnce({items:[{id:"candidate-1",candidateType:"RISK",title:"Capacity concern",description:"Candidate from a legacy persisted record",confidence:.7}]});mocks.getRAIDHygiene.mockResolvedValueOnce({});mocks.getRAIDDetail.mockResolvedValueOnce({item:items[0]});setup("/raid/risk-1");expect(await screen.findByText("Capacity concern")).toBeInTheDocument();expect(screen.getByText("0 authorized sources")).toBeInTheDocument();expect(screen.getByText("0 possible")).toBeInTheDocument();expect(await screen.findByRole("dialog",{name:/R-031/})).toBeInTheDocument();expect(screen.getByText("No authorized evidence is linked.")).toBeInTheDocument();expect(screen.getByText("No additional typed relationships are linked.")).toBeInTheDocument();expect(screen.getByText("0 findings")).toBeInTheDocument();});
  it("saves a review and proposal without external execution",async()=>{mocks.reviewRAIDItem.mockResolvedValue({});mocks.createRAIDProposal.mockResolvedValue({proposal:{id:"p-1",status:"PROPOSED"},externalWrites:false});setup("/raid/risk-1");expect(await screen.findByRole("dialog",{name:/R-031/})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Add review note"}));fireEvent.change(screen.getByLabelText("Review note"),{target:{value:"Reviewed persisted evidence."}});fireEvent.click(screen.getByRole("button",{name:"Save review"}));await waitFor(()=>expect(mocks.reviewRAIDItem).toHaveBeenCalled());expect(screen.getByRole("status")).toHaveTextContent("durable history");fireEvent.click(screen.getByRole("button",{name:"Propose intervention"}));fireEvent.change(screen.getByLabelText("Draft intervention"),{target:{value:"Draft an internal escalation."}});fireEvent.click(screen.getByRole("button",{name:"Save as proposed"}));await waitFor(()=>expect(mocks.createRAIDProposal).toHaveBeenCalled());expect(screen.getByRole("status")).toHaveTextContent("Nothing was executed externally");});
});
