import { ExternalLink, FileSearch, ShieldCheck } from "lucide-react";

export default function StructuredDeliveryResponse({response,onPropose}){
  if(!response)return null;
  return <section className="mt-5 border-t border-stone-200 pt-5" aria-label={`${response.type||"Delivery"} structured response`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#a00028]">{response.type||"Delivery analysis"}</p><h3 className="font-display mt-1 text-xl font-bold text-stone-950">{response.title}</h3></div><div className="border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900">{response.confidence??0}% confidence</div></div>
  {response.status&&<p className="mt-4 border-l-4 border-[#e65b19] bg-[#faf8f5] p-3 text-sm font-semibold text-stone-800">Status: {response.status}</p>}
  {response.findings?.length>0&&<ul className="mt-4 space-y-2 text-sm leading-6 text-stone-700">{response.findings.map(item=><li key={item} className="flex gap-2"><span aria-hidden="true" className="text-[#e65b19]">—</span>{item}</li>)}</ul>}
  {response.limitations?.length>0&&<div className="mt-4 border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><strong>Evidence limitations:</strong> {response.limitations.join(" ")}</div>}
  <div className="mt-5"><h4 className="flex items-center gap-2 text-sm font-bold text-stone-900"><FileSearch className="h-4 w-4"/>Sources and evidence</h4>{response.evidence?.length?<div className="mt-2 grid gap-2 sm:grid-cols-2">{response.evidence.map(source=><article key={source.id} className="border border-stone-200 bg-white p-3"><p className="text-sm font-semibold">{source.title}</p><p className="mt-1 text-xs leading-5 text-stone-500">{source.summary}</p><span className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-[#a00028]">{source.sourceType}<ExternalLink className="h-3 w-3"/></span></article>)}</div>:<p className="mt-2 text-sm text-stone-500">No authorized evidence was available. Axiom has not inferred a conclusion.</p>}</div>
  {response.suggestedActions?.length>0&&<div className="mt-5 flex flex-wrap gap-2">{response.suggestedActions.map(action=><button key={action} type="button" onClick={()=>onPropose?.(action,response)} className="inline-flex items-center gap-2 border border-[#a00028] px-3 py-2 text-sm font-semibold text-[#a00028] focus:outline-none focus:ring-2 focus:ring-[#ffb600]"><ShieldCheck className="h-4 w-4"/>{action}</button>)}</div>}</section>;
}
