import type {HTMLAttributes,ReactNode} from "react";
import {AlertTriangle,CheckCircle2,CircleHelp,Info,ShieldAlert} from "lucide-react";
import {Link} from "react-router-dom";
import {Button} from "../ui/button";
import {cn} from "../../lib/utils";

export {Button};

export function Surface({accent=false,className,...props}:HTMLAttributes<HTMLElement>&{accent?:boolean}){return <section className={cn("axiom-surface p-5",accent&&"axiom-surface-accent",className)} {...props}/>}

const statusMap:Record<string,{tone:string;icon:typeof Info}>={healthy:{tone:"border-emerald-200 bg-[var(--axiom-status-success-bg)] text-[var(--axiom-status-success)]",icon:CheckCircle2},active:{tone:"border-emerald-200 bg-[var(--axiom-status-success-bg)] text-[var(--axiom-status-success)]",icon:CheckCircle2},approved:{tone:"border-emerald-200 bg-[var(--axiom-status-success-bg)] text-[var(--axiom-status-success)]",icon:CheckCircle2},warning:{tone:"border-amber-200 bg-[var(--axiom-status-warning-bg)] text-[var(--axiom-status-warning)]",icon:AlertTriangle},"at risk":{tone:"border-amber-200 bg-[var(--axiom-status-warning-bg)] text-[var(--axiom-status-warning)]",icon:AlertTriangle},critical:{tone:"border-red-200 bg-[var(--axiom-status-danger-bg)] text-[var(--axiom-status-danger)]",icon:ShieldAlert},failed:{tone:"border-red-200 bg-[var(--axiom-status-danger-bg)] text-[var(--axiom-status-danger)]",icon:ShieldAlert},blocked:{tone:"border-red-200 bg-[var(--axiom-status-danger-bg)] text-[var(--axiom-status-danger)]",icon:ShieldAlert},unknown:{tone:"border-stone-200 bg-[var(--axiom-status-unknown-bg)] text-[var(--axiom-status-unknown)]",icon:CircleHelp}};
export function StatusBadge({value}:{value:string|null|undefined}){const label=value?.trim()||"Unknown",config=statusMap[label.toLowerCase()]||{tone:"border-blue-200 bg-[var(--axiom-status-info-bg)] text-[var(--axiom-status-info)]",icon:Info},Icon=config.icon;return <span className={cn("inline-flex items-center gap-1 rounded-[var(--axiom-radius-pill)] border px-2 py-1 text-xs font-semibold",config.tone)}><Icon aria-hidden size={12}/>{label}</span>}
export function Confidence({value}:{value:"high"|"medium"|"low"|"insufficient"}){const labels={high:"High confidence",medium:"Medium confidence",low:"Low confidence",insufficient:"Insufficient evidence"};return <span className="inline-flex items-center gap-2 text-xs font-semibold"><span aria-hidden className={cn("h-2 w-2",value==="high"?"bg-emerald-600":value==="medium"?"bg-amber-500":value==="low"?"bg-red-600":"bg-stone-400")}/>{labels[value]}</span>}

export function PageHeader({eyebrow,breadcrumbs=[],title,description,status,actions,lastRefreshed}:{eyebrow?:string;breadcrumbs?:{label:string;to:string}[];title:string;description?:string;status?:string;actions?:ReactNode;lastRefreshed?:string}){return <header className="border-b border-[var(--axiom-border-default)] pb-5"><nav aria-label="Breadcrumb" className="mb-3 flex flex-wrap gap-2 text-xs text-[var(--axiom-text-muted)]"><Link to="/">Axiom</Link>{breadcrumbs.map(item=><span key={item.to}>/ <Link className="hover:underline" to={item.to}>{item.label}</Link></span>)}</nav><div className="flex flex-wrap items-start justify-between gap-4"><div>{eyebrow&&<p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--axiom-brand-primary)]">{eyebrow}</p>}<div className="mt-1 flex flex-wrap items-center gap-3"><h1 className="font-display text-3xl font-bold md:text-4xl">{title}</h1>{status&&<StatusBadge value={status}/>}</div>{description&&<p className="mt-2 max-w-3xl text-sm text-[var(--axiom-text-secondary)]">{description}</p>}{lastRefreshed&&<p className="axiom-caption mt-2">Last refreshed {lastRefreshed}</p>}</div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div></header>}

export function Tabs({items}:{items:{label:string;to:string;active?:boolean;count?:number}[]}){return <nav aria-label="Section navigation" className="axiom-tabs">{items.map(item=><Link key={item.to} to={item.to} aria-current={item.active?"page":undefined} className="axiom-tab inline-flex items-center gap-2">{item.label}{item.count!==undefined&&<span className="rounded-[var(--axiom-radius-pill)] bg-stone-100 px-1.5 text-xs">{item.count}</span>}</Link>)}</nav>}

export function KpiCard({label,value,detail,status}:{label:string;value:ReactNode;detail?:string;status?:string}){return <Surface className="min-w-0"><p className="text-xs font-bold uppercase tracking-wide text-[var(--axiom-text-muted)]">{label}</p><div className="mt-2 flex items-end justify-between gap-3"><strong className="tabular-nums text-2xl font-bold">{value??"Unknown"}</strong>{status&&<StatusBadge value={status}/>}</div>{detail&&<p className="axiom-caption mt-2">{detail}</p>}</Surface>}

export function FormField({label,id,description,error,children,required=false}:{label:string;id:string;description?:string;error?:string;children:ReactNode;required?:boolean}){return <div className="grid gap-2"><label htmlFor={id} className="text-sm font-semibold">{label}{required&&<span aria-hidden className="text-red-700"> *</span>}</label>{description&&<p id={`${id}-description`} className="axiom-caption">{description}</p>}{children}{error&&<p id={`${id}-error`} role="alert" className="text-xs font-semibold text-[var(--axiom-status-danger)]">{error}</p>}</div>}

export function StatePanel({kind="empty",title,description,action}:{kind?:"empty"|"error"|"forbidden"|"insufficient";title:string;description:string;action?:ReactNode}){const Icon=kind==="error"?AlertTriangle:kind==="forbidden"?ShieldAlert:kind==="insufficient"?CircleHelp:Info;return <Surface className="flex min-h-52 flex-col items-center justify-center text-center" role={kind==="error"?"alert":undefined}><Icon className="text-[var(--axiom-brand-primary)]"/><h2 className="mt-3 font-display text-xl font-bold">{title}</h2><p className="mt-2 max-w-lg text-sm text-[var(--axiom-text-secondary)]">{description}</p>{action&&<div className="mt-4">{action}</div>}</Surface>}

export function PageTemplate({children,className}:HTMLAttributes<HTMLElement>){return <main className={cn("axiom-page",className)}><div className="axiom-content">{children}</div></main>}
export function ListTemplate({header,toolbar,children}: {header:ReactNode;toolbar?:ReactNode;children:ReactNode}){return <PageTemplate><div className="grid gap-5">{header}{toolbar&&<Surface>{toolbar}</Surface>}{children}</div></PageTemplate>}
export function ConfigurationTemplate({header,navigation,children}: {header:ReactNode;navigation?:ReactNode;children:ReactNode}){return <PageTemplate><div className="grid gap-5">{header}{navigation}{children}</div></PageTemplate>}
