import {useEffect,useMemo,useState} from "react";
import {Link,useLocation,useParams} from "react-router-dom";
import {ArrowRight,Database,RefreshCw} from "lucide-react";
import {governanceApi,type GovernanceOverview,type OperationsOverview,type Page,type Policy} from "../../services/governance.service";

type LoadState<T>={status:"loading"|"ready"|"error";data?:T;error?:string};
const labels:Record<string,string>={policy_compliance:"Policy Compliance",open_governance_findings:"Open Governance Findings",access_reviews_due:"Access Reviews Due",approval_compliance:"Approval Compliance",audit_coverage:"Audit Coverage",ai_executions:"AI Executions",success_rate:"Success Rate",p95_latency:"P95 Latency",evidence_grounded_responses:"Evidence-Grounded Responses",policy_blocks:"Policy Blocks",approval_rate:"Approval Rate",estimated_cost:"Estimated Cost",open_incidents:"Open Incidents"};
const text=(value:unknown)=>value===null||value===undefined?"Not available":typeof value==="object"?JSON.stringify(value):String(value);
const titleCase=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

function useLoad<T>(loader:()=>Promise<T>,key:string){
  const [refresh,setRefresh]=useState(0);const [state,setState]=useState<LoadState<T>>({status:"loading"});
  useEffect(()=>{let active=true;setState({status:"loading"});loader().then(data=>active&&setState({status:"ready",data})).catch(error=>active&&setState({status:"error",error:error?.response?.data?.detail?.message||"The governed data source is unavailable."}));return()=>{active=false};},[key,refresh]);
  return {state,retry:()=>setRefresh(value=>value+1)};
}
function Frame({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:React.ReactNode}){return <main className="min-h-full bg-[#f4f1ed] p-5 text-stone-900 md:p-8"><header className="border-b border-stone-300 pb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a00028]">{eyebrow}</p><h1 className="mt-2 font-display text-3xl font-bold md:text-4xl">{title}</h1><p className="mt-2 max-w-3xl text-sm text-stone-600 md:text-base">{description}</p></header>{children}</main>}
function Loading(){return <div aria-live="polite" className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-28 animate-pulse border border-stone-200 bg-white"/>)}</div>}
function ErrorState({message,retry}:{message?:string;retry:()=>void}){return <section role="alert" className="mt-8 border border-red-300 bg-red-50 p-6"><h2 className="font-semibold text-red-900">Governed data could not be loaded</h2><p className="mt-2 text-sm text-red-800">{message}</p><button onClick={retry} className="mt-4 inline-flex items-center gap-2 bg-[#a00028] px-4 py-2 text-sm font-semibold text-white"><RefreshCw size={16}/>Retry</button></section>}
function Empty({label}:{label:string}){return <section className="mt-8 border border-dashed border-stone-300 bg-white p-8 text-center"><Database className="mx-auto text-stone-400"/><h2 className="mt-3 font-semibold">No {label}</h2><p className="mt-1 text-sm text-stone-500">No persisted records match the current tenant and filters.</p></section>}
function Cards({values}:{values?:Record<string,unknown>}){return <section aria-label="Summary" className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(values??{}).map(([key,value])=><article key={key} className="border border-stone-300 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wide text-stone-500">{labels[key]||titleCase(key)}</p><p className="mt-3 text-2xl font-bold">{text(value)}</p>{value==null&&<p className="mt-1 text-xs text-amber-700">Source has not produced this measure.</p>}</article>)}</section>}
function Table({items,detailBase}:{items:Array<Record<string,unknown>>;detailBase?:string}){const columns=useMemo(()=>Object.keys(items[0]||{}).filter(key=>!["conditions","effect","cases","timeline","safe_metadata","access_items"].includes(key)).slice(0,8),[items]);if(!items.length)return <Empty label="records"/>;return <div className="mt-8 overflow-x-auto border border-stone-300 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-stone-100 text-xs uppercase tracking-wide text-stone-600"><tr>{columns.map(c=><th className="px-4 py-3" key={c}>{titleCase(c)}</th>)}</tr></thead><tbody>{items.map((item,index)=><tr key={String(item.id||item.event_id||index)} className="border-t border-stone-200">{columns.map(c=><td className="max-w-64 px-4 py-3" key={c}>{c==="id"&&detailBase?<Link className="font-semibold text-[#a00028] underline" to={`${detailBase}/${item[c]}`}>{text(item[c])}</Link>:text(item[c])}</td>)}</tr>)}</tbody></table></div>}

export function GovernanceDashboard(){const {state,retry}=useLoad<GovernanceOverview>(governanceApi.overview,"governance");const data=state.data;const attention=data?.attention??[];return <Frame eyebrow="Administration" title="Governance" description="Manage AI policies, permissions, auditability, data controls, and human oversight.">{state.status==="loading"?<Loading/>:state.status==="error"?<ErrorState message={state.error} retry={retry}/>:<><Cards values={data?.summary}/><section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="border border-stone-300 bg-white p-6"><h2 className="font-display text-xl font-bold">Attention required</h2>{attention.length?<Table items={attention}/>:<p className="mt-4 text-sm text-stone-500">No persisted governance finding currently requires attention.</p>}</article><article className="border border-stone-300 bg-white p-6"><h2 className="font-display text-xl font-bold">Human oversight</h2><dl className="mt-4 space-y-3">{Object.entries(data?.human_oversight??{}).map(([k,v])=><div className="flex justify-between gap-4 border-b border-stone-100 pb-2" key={k}><dt>{titleCase(k)}</dt><dd className="font-semibold">{text(v)}</dd></div>)}</dl></article></section><p className="mt-5 text-xs text-stone-500">Sources: {(data?.sources??[]).join(", ")||"Not available"}</p></>}</Frame>}
export function PoliciesPage(){const {state,retry}=useLoad<Page<Policy>>(governanceApi.policies,"policies");return <Frame eyebrow="Governance" title="Versioned policies" description="Deterministic policies with immutable active versions and human-controlled activation.">{state.status==="loading"?<Loading/>:state.status==="error"?<ErrorState message={state.error} retry={retry}/>:<Table items={state.data!.items as unknown as Array<Record<string,unknown>>} detailBase="/governance/policies"/>}</Frame>}
export function PolicyDetailPage(){const {policyId=""}=useParams();const {state,retry}=useLoad<Policy>(()=>governanceApi.policy(policyId),policyId);const [simulation,setSimulation]=useState<Record<string,unknown>|null>(null);return <Frame eyebrow="Governance policy" title={state.data?.name||"Policy detail"} description="Version, effect, approval history, and safe synthetic simulation.">{state.status==="loading"?<Loading/>:state.status==="error"?<ErrorState message={state.error} retry={retry}/>:<div className="mt-8 grid gap-6 lg:grid-cols-[2fr_1fr]"><article className="border border-stone-300 bg-white p-6"><Cards values={{status:state.data!.status,version:state.data!.version,category:state.data!.category,priority:state.data!.priority}}/><h2 className="mt-6 font-semibold">Declarative conditions</h2><pre className="mt-2 overflow-auto bg-stone-900 p-4 text-xs text-stone-100">{JSON.stringify(state.data!.conditions,null,2)}</pre></article><aside className="border border-stone-300 bg-white p-6"><h2 className="font-semibold">Draft simulation</h2><p className="mt-2 text-sm text-stone-600">Runs a synthetic scenario without changing active state.</p><button onClick={()=>governanceApi.simulate(policyId,{classification:"CONFIDENTIAL",targets:["model"]}).then(setSimulation)} className="mt-4 bg-[#a00028] px-4 py-2 text-sm font-semibold text-white">Run simulation</button>{simulation&&<pre aria-live="polite" className="mt-4 overflow-auto bg-stone-100 p-3 text-xs">{JSON.stringify(simulation,null,2)}</pre>}</aside></div>}</Frame>}

type ListingConfig={title:string;description:string;loader:()=>Promise<Page>;detailBase?:string};
function Listing({config}:{config:ListingConfig}){const {state,retry}=useLoad<Page>(config.loader,config.title);return <Frame eyebrow="Governance and operations" title={config.title} description={config.description}>{state.status==="loading"?<Loading/>:state.status==="error"?<ErrorState message={state.error} retry={retry}/>:<Table items={state.data!.items} detailBase={config.detailBase}/>}</Frame>}
export const PermissionsPage=()=> <Listing config={{title:"Permission catalogue",description:"Existing claim permissions, effective role inheritance, conflicts, and high-risk access.",loader:async()=>{const [permissions,roles]=await Promise.all([governanceApi.permissions(),governanceApi.roles()]);return {...permissions,items:[...permissions.items,...roles.items]}}}}/>;
export const AccessReviewsPage=()=> <Listing config={{title:"Access reviews",description:"Tenant-scoped review campaigns, reviewers, recommendations, evidence, due dates, and decisions.",loader:governanceApi.accessReviews}}/>;
export const AuditExplorerPage=()=> <Listing config={{title:"Audit Explorer",description:"Append-only, redacted governance history with trace correlation and integrity status.",loader:governanceApi.audit,detailBase:"/governance/audit"}}/>;
export const DataControlsPage=()=> <Listing config={{title:"Data controls",description:"Classification, allowed models and providers, export controls, and safe retention previews.",loader:governanceApi.retention}}/>;

export function AIOperationsDashboard(){const {state,retry}=useLoad<OperationsOverview>(governanceApi.operations,"operations");const data=state.data;return <Frame eyebrow="Administration" title="AI Operations" description="Operational health, quality, policy, token usage, cost, and incidents from persisted telemetry.">{state.status==="loading"?<Loading/>:state.status==="error"?<ErrorState message={state.error} retry={retry}/>:<><Cards values={data?.summary}/><section className="mt-8 border border-stone-300 bg-white p-6"><h2 className="font-display text-xl font-bold">Operational signals</h2><p className="mt-2 text-sm text-stone-500">Charts remain empty until persisted time-series telemetry is available; missing measures are never converted to zero.</p></section><p className="mt-5 text-xs text-stone-500">Sources: {(data?.sources??[]).join(", ")||"Not available"}</p></>}</Frame>}
export const ExecutionsPage=()=> <Listing config={{title:"Execution Explorer",description:"Trace AI requests through context, evidence, model, tools, policy, approval, actions, and verification.",loader:governanceApi.executions,detailBase:"/ai-operations/executions"}}/>;
export const EvaluationsPage=()=> <Listing config={{title:"AI evaluations",description:"Versioned datasets and deterministic security, evidence, schema, policy, latency, and cost checks.",loader:governanceApi.evaluations,detailBase:"/ai-operations/evaluations"}}/>;
export const IncidentsPage=()=> <Listing config={{title:"AI incidents",description:"Tenant-safe operational incidents, severity, ownership, mitigation, root cause, and corrective actions.",loader:governanceApi.incidents}}/>;
export function CostsPage(){const {state,retry}=useLoad<Record<string,unknown>>(async()=>{const [costs,budgets]=await Promise.all([governanceApi.costs(),governanceApi.budgets()]);return {...costs,budgets:budgets.items}},"costs");return <Frame eyebrow="AI Operations" title="Costs and budgets" description="Versioned pricing, settled usage, active reservations, reconciliation, thresholds, and governed hard limits.">{state.status==="loading"?<Loading/>:state.status==="error"?<ErrorState message={state.error} retry={retry}/>:<><Cards values={{settled_spend:state.data!.current_spend,active_reservations:state.data!.active_reservations,budget:state.data!.budget,forecast:state.data!.forecast,cost_per_execution:state.data!.cost_per_execution,blocked_calls:state.data!.blocked_calls,reconciliation_issues:state.data!.reconciliation_issues}}/><Table items={(state.data!.budgets as Array<Record<string,unknown>>)||[]} detailBase="/ai-operations/budgets"/><p className="mt-4 text-xs text-stone-500">Forecast method: {text(state.data!.forecast_method)}</p></>}</Frame>}
export const ModelsPage=()=> <Listing config={{title:"Model registry",description:"Approved providers, model configurations, use cases, classifications, regions, pricing, and history.",loader:governanceApi.models,detailBase:"/models"}}/>;

export function GovernedDetailPage(){const location=useLocation();const params=useParams();const isAudit=location.pathname.includes("/audit/");const isEvaluation=location.pathname.includes("/evaluations/");const isExecution=location.pathname.includes("/executions/");const isBudget=location.pathname.includes("/budgets/");const id=params.eventId||params.evaluationId||params.executionId||params.budgetId||params.modelId||"";const loader=isAudit?()=>governanceApi.auditEvent(id):isEvaluation?()=>governanceApi.evaluation(id):isExecution?()=>governanceApi.execution(id):isBudget?()=>governanceApi.budget(id):()=>governanceApi.model(id);const {state,retry}=useLoad<Record<string,unknown>>(loader,location.pathname);return <Frame eyebrow="Correlated detail" title={isAudit?"Audit event":isEvaluation?"Evaluation run":isExecution?"Execution trace":isBudget?"Budget control":"Model configuration"} description="Versioned evidence with tenant-scoped direct-link protection.">{state.status==="loading"?<Loading/>:state.status==="error"?<ErrorState message={state.error} retry={retry}/>:<article className="mt-8 border border-stone-300 bg-white p-6"><pre className="overflow-auto whitespace-pre-wrap text-sm">{JSON.stringify(state.data,null,2)}</pre><Link to={isAudit?"/governance/audit":isEvaluation?"/ai-operations/evaluations":isExecution?"/ai-operations/executions":isBudget?"/ai-operations/costs":"/models"} className="mt-6 inline-flex items-center gap-2 font-semibold text-[#a00028]">Back to list <ArrowRight size={16}/></Link></article>}</Frame>}
