from __future__ import annotations

from dataclasses import dataclass, field
from uuid import UUID, uuid4

from app.runtime.task import Task


@dataclass(slots=True)
class ExecutionPlan:
    """
    Output generated by the Planner.

    Contains:
    - Workflow goal
    - Tasks to execute
    - Agent capability requirements
    - Execution estimates
    """

    goal: str

    tasks: list[Task]

    plan_id: UUID = field(default_factory=uuid4)
    execution_id: UUID | None = None
    intent: str | None = None
    version: int = 1
    root_task_ids: list[UUID] = field(default_factory=list)
    status: str = "VALIDATED"
    metadata: dict[str, object] = field(default_factory=dict)
    input_fingerprint: str | None = None

    # ------------------------------------------------------------------
    # Agent Routing Information
    # ------------------------------------------------------------------

    """
    Required capabilities for the workflow.

    Example:

    [
        "report-generation",
        "data-analysis"
    ]
    """

    required_capabilities: list[str] = field(default_factory=list)

    """
    Task-level capability mapping.

    Example:

    {
        "Generate Report": [
            "report-generation"
        ]
    }
    """

    agent_requirements: dict[str, list[str]] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Execution Estimation
    # ------------------------------------------------------------------

    estimated_duration_seconds: float | None = None

    estimated_cost: float | None = None
