import api from "./api";
import { getMockDependencies, getMockDependencyDetail, getMockDependencyScenario, mockBottlenecks, mockCriticalPaths, mockDependencyGraph, mockDependencySummary, mockDetectedDependencies } from "../pages/dependencies/data/mockDependencies";
import {isDeliveryMockMode} from "../config/deliveryDataMode";

export interface DependencyEndpoint { key:string; entityType:string; entityId:string; name:string }
export interface DependencyHealth { score:number|null; status:"GREEN"|"AMBER"|"RED"|"UNKNOWN"; dataCompleteness:number; limitations:string[]; definitionVersion:string }
export interface DependencyPriority { score:number; band:"CRITICAL"|"HIGH"|"MEDIUM"|"LOW"; triggeredFactors:Array<{factor:string;points:number}>; affectedEntities:string[]; ruleVersion:string }
export interface DependencyItem { id:string;reference:string;name:string;description:string;dependencyType:string;relationshipType:string;status:string;health:DependencyHealth;priority:DependencyPriority;impact?:string;ownerId?:string;providerOwnerId?:string;consumerOwnerId?:string;provider?:DependencyEndpoint;consumer?:DependencyEndpoint;requiredByDate?:string;committedResolutionDate?:string;forecastResolutionDate?:string;actualResolutionDate?:string;identifiedAt:string;acknowledgedAt?:string;blockedSince?:string;lastReviewedAt?:string;nextReviewDate?:string;criticalPath:boolean;external:boolean;sourceSystem:string;sourceUrl?:string;projectId:string;ageDays:number;evidenceCount:number;downstreamCount:number;version:number;updatedAt:string }
export interface DependencyList { items:DependencyItem[];page:number;pageSize:number;total:number;pages:number;generatedAt:string;source:string }
export interface DependencySummary { criticalDependencies:number;atRiskDependencies:number;blockedDependencies:number;overdueDependencies:number;unownedDependencies:number;criticalPaths:number;generatedAt:string;source:string }
export interface DependencyGraph { nodes:Array<{id:string;entityType:string;entityId:string;name:string;upstreamCount:number;downstreamCount:number}>;edges:Array<{id:string;reference:string;source:string;target:string;relationshipType:string;status:string;criticalPath:boolean}>;nodeCount:number;edgeCount:number;traceId:string;generatedAt:string }
export interface DependencyDetail { item:DependencyItem;upstream:Array<{id:string;depth:number}>;downstream:Array<{id:string;depth:number}>;evidence:Array<{id:string;title:string;summary?:string;sourceType:string;sourceSystem:string;sourceUrl?:string;capturedAt:string}>;recommendations:Array<Record<string,unknown>>;recommendationDrafts:Array<{recommendation:string;reason:string;priority:string;proposedActionType:string;limitations:string[]}>;proposals:Array<{id:string;actionType:string;content:string;status:string;createdAt:string}>;scenarios:Array<{id:string;changeType:string;changeValue:Record<string,unknown>;difference:Record<string,unknown>;createdAt:string}>;history:Array<{id:string;eventType:string;previousStatus?:string;newStatus?:string;note?:string;actorId:string;changedAt:string}>;relatedRAID:Array<{id:string;reference:string;name:string;status:string}>;externalWrites:false }
export interface DependencyFilters {status?:string;priority?:string;owner_id?:string;project_id?:string;search?:string;external?:boolean;critical_path?:boolean;overdue?:boolean;unowned?:boolean;page?:number;page_size?:number;sort?:string;direction?:"asc"|"desc"}

const useMockData=isDeliveryMockMode;
export const getDependencies=async(filters:DependencyFilters={},signal?:AbortSignal)=>useMockData()?getMockDependencies(filters):(await api.get<DependencyList>("/api/dependencies",{params:filters,signal})).data;
export const getDependencySummary=async(signal?:AbortSignal)=>useMockData()?mockDependencySummary:(await api.get<DependencySummary>("/api/dependencies/summary",{signal})).data;
export const getDependencyGraph=async(signal?:AbortSignal)=>useMockData()?mockDependencyGraph:(await api.get<DependencyGraph>("/api/dependencies/graph",{signal})).data;
export const getCriticalPaths=async(signal?:AbortSignal)=>useMockData()?{items:mockCriticalPaths}:(await api.get("/api/dependencies/critical-paths",{signal})).data as {items:Array<Record<string,unknown>>};
export const getBottlenecks=async(signal?:AbortSignal)=>useMockData()?{items:mockBottlenecks}:(await api.get("/api/dependencies/bottlenecks",{signal})).data as {items:Array<Record<string,unknown>>};
export const getDetectedDependencies=async(signal?:AbortSignal)=>useMockData()?{items:mockDetectedDependencies}:(await api.get("/api/dependencies/detected",{signal})).data as {items:Array<Record<string,unknown>>};
export const getDependencyDetail=async(id:string,signal?:AbortSignal)=>{if(useMockData()){const detail=getMockDependencyDetail(id);if(!detail)throw new Error("Dependency not found");return detail;}return (await api.get<DependencyDetail>(`/api/dependencies/${encodeURIComponent(id)}`,{signal})).data};
export const createDependency=async(payload:Record<string,unknown>)=>(await api.post("/api/dependencies",payload)).data;
export const acknowledgeDependency=async(id:string,version:number)=>(await api.post(`/api/dependencies/${encodeURIComponent(id)}/acknowledge`,{version})).data;
export const transitionDependency=async(id:string,version:number,status:string,reason?:string)=>(await api.post(`/api/dependencies/${encodeURIComponent(id)}/transition`,{version,status,reason})).data;
export const runDependencyScenario=async(id:string,slipDays:number,save=false)=>useMockData()?getMockDependencyScenario(id,slipDays):(await api.post("/api/dependencies/graph/scenarios",{dependency_id:id,slip_days:slipDays,save})).data;
export const createDependencyProposal=async(id:string,payload:Record<string,unknown>)=>(await api.post(`/api/dependencies/${encodeURIComponent(id)}/proposals`,payload)).data;
export const dismissDependencyCandidate=async(id:string,reason:string)=>(await api.post(`/api/dependencies/detected/${encodeURIComponent(id)}/dismiss`,{reason})).data;
