"""add durable delivery domain

Revision ID: aae403476012
Revises: g3c5e7f9a1b4
Create Date: 2026-08-14 19:54:38.414771

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aae403476012'
down_revision: str | Sequence[str] | None = 'g3c5e7f9a1b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_delivery_tables() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_delivery_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'conversation_id', 'entity_type', 'entity_id')
    )
    op.create_index('ix_context_tenant_conversation', 'conversation_delivery_contexts', ['tenant_id', 'conversation_id'], unique=False)
    op.create_table('delivery_copilot_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=80), nullable=False),
    sa.Column('trace_id', sa.String(length=80), nullable=True),
    sa.Column('feedback_type', sa.String(length=40), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_tenant_conversation', 'delivery_copilot_feedback', ['tenant_id', 'conversation_id'], unique=False)
    op.create_table('delivery_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'source_system', 'source_record_id', 'content_hash')
    )
    op.create_index('ix_delivery_evidence_tenant_captured', 'delivery_evidence', ['tenant_id', 'captured_at'], unique=False)
    op.create_index('ix_delivery_evidence_tenant_entity', 'delivery_evidence', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('delivery_portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_portfolio_tenant_status', 'delivery_portfolios', ['tenant_id', 'status'], unique=False)
    op.create_table('delivery_proposed_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_classification', sa.String(length=30), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_proposed_action_tenant_owner', 'delivery_proposed_actions', ['tenant_id', 'owner_id'], unique=False)
    op.create_index('ix_proposed_action_tenant_status', 'delivery_proposed_actions', ['tenant_id', 'status'], unique=False)
    op.create_table('delivery_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_recommendation_tenant_status', 'delivery_recommendations', ['tenant_id', 'status'], unique=False)
    op.create_table('delivery_programmes',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'portfolio_id'], ['delivery_portfolios.tenant_id', 'delivery_portfolios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_programme_tenant_portfolio', 'delivery_programmes', ['tenant_id', 'portfolio_id'], unique=False)
    op.create_table('delivery_proposed_action_evidence',
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('proposed_action_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'evidence_id'], ['delivery_evidence.tenant_id', 'delivery_evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'proposed_action_id'], ['delivery_proposed_actions.tenant_id', 'delivery_proposed_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'proposed_action_id', 'evidence_id')
    )
    op.create_table('delivery_recommendation_evidence',
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'evidence_id'], ['delivery_evidence.tenant_id', 'delivery_evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'recommendation_id'], ['delivery_recommendations.tenant_id', 'delivery_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'recommendation_id', 'evidence_id')
    )
    op.create_table('delivery_projects',
    sa.Column('programme_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'programme_id'], ['delivery_programmes.tenant_id', 'delivery_programmes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_project_tenant_programme', 'delivery_projects', ['tenant_id', 'programme_id'], unique=False)
    op.create_table('delivery_releases',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'project_id'], ['delivery_projects.tenant_id', 'delivery_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_release_tenant_project', 'delivery_releases', ['tenant_id', 'project_id'], unique=False)
    op.create_table('delivery_teams',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'project_id'], ['delivery_projects.tenant_id', 'delivery_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_team_tenant_project', 'delivery_teams', ['tenant_id', 'project_id'], unique=False)
    op.create_table('delivery_sprints',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('original_committed_points', sa.Float(), nullable=True),
    sa.Column('completed_original_points', sa.Float(), nullable=True),
    sa.Column('completed_points', sa.Float(), nullable=True),
    sa.Column('scope_added_points', sa.Float(), nullable=False),
    sa.Column('scope_removed_points', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'project_id'], ['delivery_projects.tenant_id', 'delivery_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'team_id'], ['delivery_teams.tenant_id', 'delivery_teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_sprint_tenant_dates', 'delivery_sprints', ['tenant_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_delivery_sprint_tenant_team_status', 'delivery_sprints', ['tenant_id', 'team_id', 'status'], unique=False)
    op.create_table('delivery_raid_items',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sprint_id', sa.String(length=36), nullable=True),
    sa.Column('release_id', sa.String(length=36), nullable=True),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('impact', sa.String(length=30), nullable=True),
    sa.Column('probability', sa.String(length=30), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'project_id'], ['delivery_projects.tenant_id', 'delivery_projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'release_id'], ['delivery_releases.tenant_id', 'delivery_releases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'sprint_id'], ['delivery_sprints.tenant_id', 'delivery_sprints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_raid_tenant_due', 'delivery_raid_items', ['tenant_id', 'due_date'], unique=False)
    op.create_index('ix_delivery_raid_tenant_type_status', 'delivery_raid_items', ['tenant_id', 'item_type', 'status'], unique=False)
    op.create_table('delivery_work_items',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sprint_id', sa.String(length=36), nullable=True),
    sa.Column('item_kind', sa.String(length=40), nullable=False),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('assignee_id', sa.String(length=255), nullable=True),
    sa.Column('goal_critical', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_after_start', sa.Boolean(), nullable=False),
    sa.Column('removed_after_start', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'project_id'], ['delivery_projects.tenant_id', 'delivery_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'sprint_id'], ['delivery_sprints.tenant_id', 'delivery_sprints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_work_tenant_owner', 'delivery_work_items', ['tenant_id', 'assignee_id'], unique=False)
    op.create_index('ix_delivery_work_tenant_sprint_status', 'delivery_work_items', ['tenant_id', 'sprint_id', 'status'], unique=False)
    op.create_table('delivery_defects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sprint_id', sa.String(length=36), nullable=True),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('escaped', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'project_id'], ['delivery_projects.tenant_id', 'delivery_projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'sprint_id'], ['delivery_sprints.tenant_id', 'delivery_sprints.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'work_item_id'], ['delivery_work_items.tenant_id', 'delivery_work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_delivery_defect_tenant_sprint', 'delivery_defects', ['tenant_id', 'sprint_id'], unique=False)
    return
    op.alter_column('actions', 'permissions',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('uq_action_tenant_connection_name'), table_name='actions')
    op.create_index(op.f('ix_agent_versions_tenant_id'), 'agent_versions', ['tenant_id'], unique=False)
    op.alter_column('agents', 'configuration',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('agents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_approval_resume_token', 'approval_requests', ['resume_token_hash'])
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_audit_correlation'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_tenant_created'), table_name='audit_logs')
    op.create_unique_constraint('uq_clarification_resume_token', 'clarification_requests', ['resume_token_hash'])
    op.alter_column('conversations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_integration_configurations_tenant_id'), 'integration_configurations', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_knowledge_tenant_readiness'), table_name='knowledge_sources')
    op.create_index(op.f('ix_knowledge_sources_tenant_id'), 'knowledge_sources', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mcp_capabilities_fingerprint'), 'mcp_capabilities', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_mcp_capabilities_server_id'), 'mcp_capabilities', ['server_id'], unique=False)
    op.create_index(op.f('ix_mcp_capabilities_tenant_id'), 'mcp_capabilities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mcp_servers_tenant_id'), 'mcp_servers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mcp_sync_runs_server_id'), 'mcp_sync_runs', ['server_id'], unique=False)
    op.create_index(op.f('ix_mcp_sync_runs_tenant_id'), 'mcp_sync_runs', ['tenant_id'], unique=False)
    op.alter_column('messages', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_native_connections'), table_name='native_connections')
    op.create_index(op.f('ix_native_connections_kind'), 'native_connections', ['kind'], unique=False)
    op.create_index(op.f('ix_native_connections_tenant_id'), 'native_connections', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_native_content_search'), table_name='native_file_contents')
    op.create_index(op.f('ix_native_file_contents_file_id'), 'native_file_contents', ['file_id'], unique=False)
    op.create_index(op.f('ix_native_file_contents_tenant_id'), 'native_file_contents', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_native_files_status'), table_name='native_files')
    op.create_index(op.f('ix_native_files_checksum'), 'native_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_native_files_owner_id'), 'native_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_native_files_processing_status'), 'native_files', ['processing_status'], unique=False)
    op.create_index(op.f('ix_native_files_tenant_id'), 'native_files', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_native_notifications'), table_name='native_notifications')
    op.create_index(op.f('ix_native_notifications_status'), 'native_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_native_notifications_tenant_id'), 'native_notifications', ['tenant_id'], unique=False)
    op.alter_column('runtime_continuations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('runtime_continuations', 'execution_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('runtime_execution_events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('runtime_execution_events', 'execution_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_runtime_events_execution_final'), table_name='runtime_execution_events')
    op.alter_column('runtime_executions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('runtime_executions', 'conversation_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('runtime_executions', 'workflow_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('runtime_executions', 'result_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('runtime_executions', 'error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_runtime_executions_stale_lease'), table_name='runtime_executions')
    op.drop_index(op.f('ix_runtime_executions_workflow_id'), table_name='runtime_executions')
    op.create_index(op.f('ix_runtime_executions_workflow_id'), 'runtime_executions', ['workflow_id'], unique=True)
    op.create_index(op.f('ix_tool_assignments_tenant_id'), 'tool_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_assignments_tool_name'), 'tool_assignments', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_candidate_decisions_discovery_id'), 'tool_candidate_decisions', ['discovery_id'], unique=False)
    op.create_index(op.f('ix_tool_candidate_decisions_tenant_id'), 'tool_candidate_decisions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_definitions_category'), 'tool_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_tool_definitions_name'), 'tool_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_tool_definitions_provider'), 'tool_definitions', ['provider'], unique=False)
    op.create_index(op.f('ix_tool_definitions_tenant_id'), 'tool_definitions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_discovery_events_actor_id'), 'tool_discovery_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_tool_discovery_events_outcome'), 'tool_discovery_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_tool_discovery_events_tenant_id'), 'tool_discovery_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_discovery_feedback_discovery_id'), 'tool_discovery_feedback', ['discovery_id'], unique=False)
    op.create_index(op.f('ix_tool_discovery_feedback_tenant_id'), 'tool_discovery_feedback', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_actor_id'), 'tool_executions', ['actor_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_status'), 'tool_executions', ['status'], unique=False)
    op.create_index(op.f('ix_tool_executions_tenant_id'), 'tool_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_name'), 'tool_executions', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_governance_policies_tenant_id'), 'tool_governance_policies', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_marketplace_profiles_tenant_id'), 'tool_marketplace_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_marketplace_profiles_tool_name'), 'tool_marketplace_profiles', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_search_index_content_fingerprint'), 'tool_search_index', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_tool_search_index_tenant_id'), 'tool_search_index', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_search_index_tool_name'), 'tool_search_index', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def _discarded_autogenerate_downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_search_index_tool_name'), table_name='tool_search_index')
    op.drop_index(op.f('ix_tool_search_index_tenant_id'), table_name='tool_search_index')
    op.drop_index(op.f('ix_tool_search_index_content_fingerprint'), table_name='tool_search_index')
    op.drop_index(op.f('ix_tool_marketplace_profiles_tool_name'), table_name='tool_marketplace_profiles')
    op.drop_index(op.f('ix_tool_marketplace_profiles_tenant_id'), table_name='tool_marketplace_profiles')
    op.drop_index(op.f('ix_tool_governance_policies_tenant_id'), table_name='tool_governance_policies')
    op.drop_index(op.f('ix_tool_executions_tool_name'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_tenant_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_status'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_actor_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_discovery_feedback_tenant_id'), table_name='tool_discovery_feedback')
    op.drop_index(op.f('ix_tool_discovery_feedback_discovery_id'), table_name='tool_discovery_feedback')
    op.drop_index(op.f('ix_tool_discovery_events_tenant_id'), table_name='tool_discovery_events')
    op.drop_index(op.f('ix_tool_discovery_events_outcome'), table_name='tool_discovery_events')
    op.drop_index(op.f('ix_tool_discovery_events_actor_id'), table_name='tool_discovery_events')
    op.drop_index(op.f('ix_tool_definitions_tenant_id'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_provider'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_name'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_category'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_candidate_decisions_tenant_id'), table_name='tool_candidate_decisions')
    op.drop_index(op.f('ix_tool_candidate_decisions_discovery_id'), table_name='tool_candidate_decisions')
    op.drop_index(op.f('ix_tool_assignments_tool_name'), table_name='tool_assignments')
    op.drop_index(op.f('ix_tool_assignments_tenant_id'), table_name='tool_assignments')
    op.drop_index(op.f('ix_runtime_executions_workflow_id'), table_name='runtime_executions')
    op.create_index(op.f('ix_runtime_executions_workflow_id'), 'runtime_executions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_runtime_executions_stale_lease'), 'runtime_executions', ['status', 'lease_expires_at'], unique=False)
    op.alter_column('runtime_executions', 'error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('runtime_executions', 'result_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('runtime_executions', 'workflow_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('runtime_executions', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('runtime_executions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_index(op.f('ix_runtime_events_execution_final'), 'runtime_execution_events', ['execution_id', 'final'], unique=False)
    op.alter_column('runtime_execution_events', 'execution_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('runtime_execution_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('runtime_continuations', 'execution_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('runtime_continuations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_native_notifications_tenant_id'), table_name='native_notifications')
    op.drop_index(op.f('ix_native_notifications_status'), table_name='native_notifications')
    op.create_index(op.f('ix_native_notifications'), 'native_notifications', ['tenant_id', 'status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_native_files_tenant_id'), table_name='native_files')
    op.drop_index(op.f('ix_native_files_processing_status'), table_name='native_files')
    op.drop_index(op.f('ix_native_files_owner_id'), table_name='native_files')
    op.drop_index(op.f('ix_native_files_checksum'), table_name='native_files')
    op.create_index(op.f('ix_native_files_status'), 'native_files', ['tenant_id', 'processing_status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_native_file_contents_tenant_id'), table_name='native_file_contents')
    op.drop_index(op.f('ix_native_file_contents_file_id'), table_name='native_file_contents')
    op.create_index(op.f('ix_native_content_search'), 'native_file_contents', ['tenant_id', 'file_id', 'sequence'], unique=False)
    op.drop_index(op.f('ix_native_connections_tenant_id'), table_name='native_connections')
    op.drop_index(op.f('ix_native_connections_kind'), table_name='native_connections')
    op.create_index(op.f('ix_native_connections'), 'native_connections', ['tenant_id', 'kind', 'enabled'], unique=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_mcp_sync_runs_tenant_id'), table_name='mcp_sync_runs')
    op.drop_index(op.f('ix_mcp_sync_runs_server_id'), table_name='mcp_sync_runs')
    op.drop_index(op.f('ix_mcp_servers_tenant_id'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_capabilities_tenant_id'), table_name='mcp_capabilities')
    op.drop_index(op.f('ix_mcp_capabilities_server_id'), table_name='mcp_capabilities')
    op.drop_index(op.f('ix_mcp_capabilities_fingerprint'), table_name='mcp_capabilities')
    op.drop_index(op.f('ix_knowledge_sources_tenant_id'), table_name='knowledge_sources')
    op.create_index(op.f('ix_knowledge_tenant_readiness'), 'knowledge_sources', ['tenant_id', 'readiness_status', 'health_status'], unique=False)
    op.drop_index(op.f('ix_integration_configurations_tenant_id'), table_name='integration_configurations')
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint('uq_clarification_resume_token', 'clarification_requests', type_='unique')
    op.create_index(op.f('ix_audit_tenant_created'), 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_correlation'), 'audit_logs', ['correlation_id'], unique=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('uq_approval_resume_token', 'approval_requests', type_='unique')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.alter_column('agents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('agents', 'configuration',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_versions_tenant_id'), table_name='agent_versions')
    op.create_index(op.f('uq_action_tenant_connection_name'), 'actions', ['tenant_id', 'integration_connection_id', 'name'], unique=1)
    op.alter_column('actions', 'permissions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('ix_delivery_defect_tenant_sprint', table_name='delivery_defects')
    op.drop_table('delivery_defects')
    op.drop_index('ix_delivery_work_tenant_sprint_status', table_name='delivery_work_items')
    op.drop_index('ix_delivery_work_tenant_owner', table_name='delivery_work_items')
    op.drop_table('delivery_work_items')
    op.drop_index('ix_delivery_raid_tenant_type_status', table_name='delivery_raid_items')
    op.drop_index('ix_delivery_raid_tenant_due', table_name='delivery_raid_items')
    op.drop_table('delivery_raid_items')
    op.drop_index('ix_delivery_sprint_tenant_team_status', table_name='delivery_sprints')
    op.drop_index('ix_delivery_sprint_tenant_dates', table_name='delivery_sprints')
    op.drop_table('delivery_sprints')
    op.drop_index('ix_delivery_team_tenant_project', table_name='delivery_teams')
    op.drop_table('delivery_teams')
    op.drop_index('ix_delivery_release_tenant_project', table_name='delivery_releases')
    op.drop_table('delivery_releases')
    op.drop_index('ix_delivery_project_tenant_programme', table_name='delivery_projects')
    op.drop_table('delivery_projects')
    op.drop_table('delivery_recommendation_evidence')
    op.drop_table('delivery_proposed_action_evidence')
    op.drop_index('ix_delivery_programme_tenant_portfolio', table_name='delivery_programmes')
    op.drop_table('delivery_programmes')
    op.drop_index('ix_delivery_recommendation_tenant_status', table_name='delivery_recommendations')
    op.drop_table('delivery_recommendations')
    op.drop_index('ix_proposed_action_tenant_status', table_name='delivery_proposed_actions')
    op.drop_index('ix_proposed_action_tenant_owner', table_name='delivery_proposed_actions')
    op.drop_table('delivery_proposed_actions')
    op.drop_index('ix_delivery_portfolio_tenant_status', table_name='delivery_portfolios')
    op.drop_table('delivery_portfolios')
    op.drop_index('ix_delivery_evidence_tenant_entity', table_name='delivery_evidence')
    op.drop_index('ix_delivery_evidence_tenant_captured', table_name='delivery_evidence')
    op.drop_table('delivery_evidence')
    op.drop_index('ix_feedback_tenant_conversation', table_name='delivery_copilot_feedback')
    op.drop_table('delivery_copilot_feedback')
    op.drop_index('ix_context_tenant_conversation', table_name='conversation_delivery_contexts')
    op.drop_table('conversation_delivery_contexts')
    # ### end Alembic commands ###


def upgrade() -> None:
    """Create only the additive, tenant-scoped delivery tables above."""
    _create_delivery_tables()


def downgrade() -> None:
    """Remove only AX-H01 delivery tables; inherited schema is untouched."""
    for table in (
        'delivery_defects', 'delivery_work_items', 'delivery_raid_items',
        'delivery_sprints', 'delivery_teams', 'delivery_releases',
        'delivery_projects', 'delivery_recommendation_evidence',
        'delivery_proposed_action_evidence', 'delivery_programmes',
        'delivery_recommendations', 'delivery_proposed_actions',
        'delivery_portfolios', 'delivery_evidence', 'delivery_copilot_feedback',
        'conversation_delivery_contexts',
    ):
        op.drop_table(table)
