"""knowledge intelligence

Revision ID: d2f4a6c8e0b3
Revises: c1f3a5b7d9e2
"""
import sqlalchemy as sa
from alembic import op
revision="d2f4a6c8e0b3";down_revision="c1f3a5b7d9e2";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("knowledge_items",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("title",sa.String(500),nullable=False),sa.Column("item_type",sa.String(60),nullable=False),sa.Column("summary",sa.Text(),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("trust_status",sa.String(30),nullable=False),sa.Column("freshness_status",sa.String(30),nullable=False),sa.Column("access_classification",sa.String(30),nullable=False),sa.Column("source_system",sa.String(60),nullable=False),sa.Column("source_record_id",sa.String(255)),sa.Column("source_url",sa.String(1000)),sa.Column("owner_id",sa.String(160),nullable=False),sa.Column("reviewers",sa.JSON(),nullable=False),sa.Column("tags",sa.JSON(),nullable=False),sa.Column("context",sa.JSON(),nullable=False),sa.Column("content_fingerprint",sa.String(64),nullable=False),sa.Column("current_version",sa.Integer(),nullable=False),sa.Column("evidence_coverage",sa.Integer()),sa.Column("last_synchronized_at",sa.DateTime(timezone=True)),sa.Column("last_verified_at",sa.DateTime(timezone=True)),sa.Column("next_review_at",sa.DateTime(timezone=True)),sa.Column("created_by",sa.String(160),nullable=False),sa.Column("updated_by",sa.String(160),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","id"))
    op.create_index("ix_knowledge_item_search","knowledge_items",["tenant_id","status","item_type","updated_at"])
    op.create_table("knowledge_item_versions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("item_id",sa.String(36),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("title",sa.String(500),nullable=False),sa.Column("summary",sa.Text(),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("content_fingerprint",sa.String(64),nullable=False),sa.Column("change_summary",sa.String(500),nullable=False),sa.Column("author_id",sa.String(160),nullable=False),sa.Column("review_status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["tenant_id","item_id"],["knowledge_items.tenant_id","knowledge_items.id"],ondelete="CASCADE"),sa.UniqueConstraint("tenant_id","item_id","version_number"))
    op.create_table("knowledge_relationships",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("item_id",sa.String(36),nullable=False),sa.Column("related_type",sa.String(50),nullable=False),sa.Column("related_id",sa.String(160),nullable=False),sa.Column("relationship_type",sa.String(50),nullable=False),sa.Column("label",sa.String(500),nullable=False),sa.Column("created_by",sa.String(160),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["tenant_id","item_id"],["knowledge_items.tenant_id","knowledge_items.id"],ondelete="CASCADE"),sa.UniqueConstraint("tenant_id","item_id","related_type","related_id","relationship_type"))
    op.create_table("knowledge_evidence_references",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("item_id",sa.String(36),nullable=False),sa.Column("evidence_id",sa.String(36),nullable=False),sa.Column("claim",sa.Text(),nullable=False),sa.Column("strength",sa.String(20),nullable=False),sa.Column("immutable",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["tenant_id","item_id"],["knowledge_items.tenant_id","knowledge_items.id"],ondelete="CASCADE"),sa.UniqueConstraint("tenant_id","item_id","evidence_id"))
    op.create_table("knowledge_decisions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("title",sa.String(500),nullable=False),sa.Column("statement",sa.Text(),nullable=False),sa.Column("rationale",sa.Text(),nullable=False),sa.Column("selected_option",sa.Text(),nullable=False),sa.Column("options",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("owner_id",sa.String(160),nullable=False),sa.Column("context",sa.JSON(),nullable=False),sa.Column("evidence_ids",sa.JSON(),nullable=False),sa.Column("approval_id",sa.String(36)),sa.Column("version",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","id"))
    op.create_index("ix_knowledge_decision_status","knowledge_decisions",["tenant_id","status","updated_at"])
    op.create_table("knowledge_templates",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("family_key",sa.String(120),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("template_type",sa.String(60),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("schema",sa.JSON(),nullable=False),sa.Column("template_version",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("owner_id",sa.String(160),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","family_key","template_version"))
def downgrade():
    for table in ["knowledge_templates","knowledge_decisions","knowledge_evidence_references","knowledge_relationships","knowledge_item_versions","knowledge_items"]:op.drop_table(table)
