import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Check, ChevronLeft, ChevronRight, Save, ShieldCheck } from "lucide-react";
import { createAgent, getAgentOptions, saveAssignments } from "../../services/agentService";

const steps = ["Basics", "Instructions", "Model & routing", "Capabilities & tools", "Knowledge", "Governance", "Validate & test", "Review"];
const categories = ["Delivery intelligence", "Sprint intelligence", "RAID analysis", "Dependency analysis", "Release readiness", "Meeting intelligence", "Executive reporting", "Governance", "General delivery support"];
const field = "mt-1 w-full rounded-xl border border-stone-300 bg-white px-3 py-2.5 text-sm text-stone-800 outline-none focus:border-[#a00028] focus:ring-2 focus:ring-[#a00028]/15 disabled:bg-stone-100";
const initial = { name: "", slug: "", description: "", purpose: "", businessOwner: "", technicalOwner: "", category: categories[0], tags: "", objective: "", instructions: "", responsibilities: "", nonResponsibilities: "", responseFormat: "Structured summary with evidence", tone: "Professional and concise", confidenceBehavior: "State confidence and explain uncertainty", insufficientEvidence: "Explicitly state that evidence is insufficient", escalationBehavior: "Escalate to the technical owner", provider: "", model: "", fallback: "", planner: "default", capabilities: [], tools: [], knowledge: [], intendedUsers: "Delivery team", environments: ["development"], dataClassification: "INTERNAL", approvalPolicy: "Human approval for mutating actions", retention: "30_days", maxSteps: 20, timeout: 120, costLimit: 5, risk: "read" };

export default function AgentCreateWizard({ onCancel, onSaved }) {
  const options = useQuery({ queryKey: ["agent-options"], queryFn: getAgentOptions });
  const [step, setStep] = useState(0);
  const [form, setForm] = useState(initial);
  const [errors, setErrors] = useState({});
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  const set = (name, value) => setForm((current) => ({ ...current, [name]: value }));
  const selectedModel = `${form.provider}:${form.model}`;
  const validation = useMemo(() => [
    { label: "Identity and ownership", pass: form.name.trim().length >= 2 && Boolean(form.businessOwner && form.technicalOwner) },
    { label: "Instructions and evidence behavior", pass: Boolean(form.objective.trim() && form.instructions.trim() && form.insufficientEvidence.trim()) },
    { label: "Governed model selected", pass: Boolean(form.provider && form.model) },
    { label: "Runtime limits", pass: Number(form.maxSteps) > 0 && Number(form.timeout) > 0 && Number(form.costLimit) >= 0 },
    { label: "Knowledge readiness", pass: form.knowledge.every((id) => options.data?.knowledge.find((item) => item.id === id)?.readiness === "ready") },
  ], [form, options.data]);
  const valid = validation.every((item) => item.pass);

  function validateCurrent() {
    const next = {};
    if (step === 0) { if (form.name.trim().length < 2) next.name = "Enter at least two characters."; if (!form.businessOwner) next.businessOwner = "Business owner is required."; if (!form.technicalOwner) next.technicalOwner = "Technical owner is required."; }
    if (step === 1 && !form.instructions.trim()) next.instructions = "System instructions are required.";
    if (step === 2 && !form.model) next.model = "Select an approved model.";
    setErrors(next);
    return Object.keys(next).length === 0;
  }
  function move(direction) { if (direction > 0 && !validateCurrent()) return; setStep((current) => Math.max(0, Math.min(steps.length - 1, current + direction))); }
  function toggle(name, value) { set(name, form[name].includes(value) ? form[name].filter((item) => item !== value) : [...form[name], value]); }
  async function saveDraft() {
    if (!valid) { setMessage("Complete the required validation checks before saving."); setStep(6); return; }
    setSaving(true); setMessage("");
    try {
      const agent = await createAgent({
        name: form.name, slug: form.slug || undefined, description: form.description || form.purpose, owner_id: form.technicalOwner,
        instructions: [form.objective, form.instructions, `Responsibilities: ${form.responsibilities}`, `Non-responsibilities: ${form.nonResponsibilities}`, `Response format: ${form.responseFormat}`, `Tone: ${form.tone}`, `Confidence: ${form.confidenceBehavior}`, `Insufficient evidence: ${form.insufficientEvidence}`, `Escalation: ${form.escalationBehavior}`].filter(Boolean).join("\n\n"),
        model_configuration: { provider: form.provider, model: form.model, fallback: form.fallback || undefined }, planner_configuration: { name: form.planner }, capabilities: form.capabilities,
        memory_configuration: { category: form.category, tags: form.tags.split(",").map((item) => item.trim()).filter(Boolean), business_owner: form.businessOwner, technical_owner: form.technicalOwner, intended_users: form.intendedUsers, data_classification: form.dataClassification, approval_policy: form.approvalPolicy, retention_policy: form.retention },
        execution_limits: { max_steps: Number(form.maxSteps), timeout_seconds: Number(form.timeout), cost_limit: Number(form.costLimit), risk_limit: form.risk, environments: form.environments }, tool_discovery_configuration: { mode: "assigned_only" }, change_note: "Created in governed agent wizard",
      });
      if (form.tools.length) await saveAssignments(agent.id, "tools", form.tools.map((name) => ({ tool_name: name, version_restriction: "active", assignment_action: "execute", enabled: true, risk_mode: options.data.tools.find((item) => item.name === name)?.risk || "read", approval_required: ["write", "destructive"].includes(options.data.tools.find((item) => item.name === name)?.risk) })));
      if (form.knowledge.length) await saveAssignments(agent.id, "knowledge", form.knowledge.map((id) => ({ knowledge_source_id: id, access_mode: "retrieve", readiness_required: true, enabled: true })));
      onSaved(agent);
    } catch (error) { setMessage(error.response?.data?.detail?.message || "The draft could not be saved."); } finally { setSaving(false); }
  }
  if (options.isLoading) return <div className="mt-6 rounded-2xl border border-stone-300 bg-white p-8 text-stone-600">Loading governed options…</div>;
  if (options.error) return <div role="alert" className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800">Agent creation options are unavailable or you do not have permission.</div>;
  return <section className="mt-6 overflow-hidden rounded-2xl border border-stone-300 bg-white shadow-sm" aria-labelledby="wizard-title">
    <div className="border-b border-stone-200 p-5"><div className="flex items-center justify-between"><div><h2 id="wizard-title" className="text-xl font-bold">Agent configuration</h2><p className="mt-1 text-sm text-stone-500">Step {step + 1} of {steps.length} · {steps[step]}</p></div><span className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">DRAFT ONLY</span></div><ol className="mt-5 grid gap-2 sm:grid-cols-4 xl:grid-cols-8">{steps.map((name, index) => <li key={name}><button type="button" onClick={() => index <= step && setStep(index)} aria-current={index === step ? "step" : undefined} className={`flex w-full items-center gap-2 rounded-xl border p-2 text-left text-xs ${index === step ? "border-[#a00028] bg-red-50 text-[#a00028]" : index < step ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-stone-200 text-stone-500"}`}><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-white">{index < step ? <Check size={13} /> : index + 1}</span><span className="truncate">{name}</span></button></li>)}</ol></div>
    <div className="min-h-[360px] p-5 md:p-7">{message && <p role="alert" className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{message}</p>}{step === 0 && <Basics form={form} set={set} errors={errors} />}{step === 1 && <Instructions form={form} set={set} errors={errors} />}{step === 2 && <Model form={form} set={set} options={options.data} error={errors.model} selected={selectedModel} />}{step === 3 && <Choice title="Approved capabilities and tools" items={options.data.tools} selected={form.tools} onToggle={(value) => toggle("tools", value)} />}{step === 4 && <Knowledge items={options.data.knowledge} selected={form.knowledge} onToggle={(value) => toggle("knowledge", value)} />}{step === 5 && <Governance form={form} set={set} />}{step === 6 && <Validation checks={validation} />}{step === 7 && <Review form={form} options={options.data} validation={validation} />}</div>
    <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-stone-200 bg-stone-50 p-5"><button type="button" onClick={onCancel} className="rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm font-semibold">Cancel</button><div className="flex gap-2"><button type="button" disabled={step === 0} onClick={() => move(-1)} className="inline-flex items-center gap-2 rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm font-semibold disabled:opacity-40"><ChevronLeft size={16} />Back</button>{step < 7 ? <button type="button" onClick={() => move(1)} className="inline-flex items-center gap-2 rounded-xl bg-[#a00028] px-4 py-2 text-sm font-semibold text-white">Next<ChevronRight size={16} /></button> : <button type="button" disabled={saving || !valid} onClick={saveDraft} className="inline-flex items-center gap-2 rounded-xl bg-[#a00028] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40"><Save size={16} />{saving ? "Saving…" : "Save draft"}</button>}</div></footer>
  </section>;
}

function L({ label, error, children }) { return <label className="block text-sm font-semibold">{label}{children}{error && <span className="mt-1 block text-xs text-red-700">{error}</span>}</label>; }
function Basics({ form, set, errors }) { return <div><h3 className="text-lg font-bold">Basic identity</h3><p className="mt-1 text-sm text-stone-500">Define ownership and the delivery purpose.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><L label="Agent name" error={errors.name}><input className={field} value={form.name} onChange={(event) => set("name", event.target.value)} /></L><L label="Stable slug"><input className={field} value={form.slug} onChange={(event) => set("slug", event.target.value)} placeholder="Generated from name when blank" /></L><L label="Business owner" error={errors.businessOwner}><input className={field} value={form.businessOwner} onChange={(event) => set("businessOwner", event.target.value)} /></L><L label="Technical owner" error={errors.technicalOwner}><input className={field} value={form.technicalOwner} onChange={(event) => set("technicalOwner", event.target.value)} /></L><L label="Category"><select className={field} value={form.category} onChange={(event) => set("category", event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></L><L label="Tags"><input className={field} value={form.tags} onChange={(event) => set("tags", event.target.value)} placeholder="release, delivery, evidence" /></L><L label="Short description"><textarea className={field} value={form.description} onChange={(event) => set("description", event.target.value)} /></L><L label="Purpose"><textarea className={field} value={form.purpose} onChange={(event) => set("purpose", event.target.value)} /></L></div></div>; }
function Instructions({ form, set, errors }) { const fields = [["objective", "Agent objective"], ["instructions", "System instructions"], ["responsibilities", "Expected responsibilities"], ["nonResponsibilities", "Explicit non-responsibilities"], ["responseFormat", "Response format"], ["tone", "Tone"], ["confidenceBehavior", "Confidence behavior"], ["insufficientEvidence", "Insufficient-evidence behavior"], ["escalationBehavior", "Escalation behavior"]]; return <div><h3 className="text-lg font-bold">Instructions and behavior</h3><div className="mt-5 grid gap-4 md:grid-cols-2">{fields.map(([name, label]) => <L key={name} label={label} error={errors[name]}><textarea className={`${field} min-h-24`} value={form[name]} onChange={(event) => set(name, event.target.value)} /></L>)}</div></div>; }
function Model({ form, set, options, error, selected }) { return <div><h3 className="text-lg font-bold">Governed model and routing</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><L label="Primary approved model" error={error}><select className={field} value={selected} onChange={(event) => { const [provider, ...rest] = event.target.value.split(":"); set("provider", provider); set("model", rest.join(":")); }}>{options.models.map((item) => <option key={`${item.provider}:${item.model}`} value={`${item.provider}:${item.model}`}>{item.label} · {item.provider}</option>)}</select></L><L label="Lower-cost fallback"><select className={field} value={form.fallback} onChange={(event) => set("fallback", event.target.value)}><option value="">No fallback</option>{options.models.filter((item) => item.model !== form.model).map((item) => <option key={item.model} value={item.model}>{item.label}</option>)}</select></L><L label="Routing policy"><select className={field} value={form.planner} onChange={(event) => set("planner", event.target.value)}>{options.planners.map((item) => <option key={item.name} value={item.name}>{item.label}</option>)}</select></L></div><p className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Runtime routing remains subject to model approval, tenant policy, data classification, evaluation status, and budget enforcement.</p></div>; }
function Choice({ title, items, selected, onToggle }) { return <div><h3 className="text-lg font-bold">{title}</h3><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <label key={item.name} className={`rounded-xl border p-4 ${selected.includes(item.name) ? "border-[#a00028] bg-red-50" : "border-stone-200"}`}><div className="flex gap-3"><input type="checkbox" checked={selected.includes(item.name)} onChange={() => onToggle(item.name)} /><div><strong>{item.display_name}</strong><p className="mt-1 text-xs text-stone-500">{item.provider} · {item.version} · {item.risk} risk</p><p className="mt-2 text-sm text-stone-600">{item.description}</p></div></div></label>)}</div></div>; }
function Knowledge({ items, selected, onToggle }) { return <div><h3 className="text-lg font-bold">Authorized knowledge</h3><div className="mt-5 grid gap-3 md:grid-cols-2">{items.map((item) => { const ready = item.readiness === "ready"; return <label key={item.id} className={`rounded-xl border p-4 ${selected.includes(item.id) ? "border-[#a00028] bg-red-50" : "border-stone-200"} ${ready ? "" : "opacity-60"}`}><div className="flex gap-3"><input type="checkbox" disabled={!ready} checked={selected.includes(item.id)} onChange={() => onToggle(item.id)} /><div><strong>{item.name}</strong><p className="mt-1 text-xs text-stone-500">{item.source_type} · {item.readiness} · {item.health}</p></div></div></label>; })}</div></div>; }
function Governance({ form, set }) { return <div><h3 className="text-lg font-bold">Governance and runtime limits</h3><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><L label="Intended users"><input className={field} value={form.intendedUsers} onChange={(event) => set("intendedUsers", event.target.value)} /></L><L label="Data classification"><select className={field} value={form.dataClassification} onChange={(event) => set("dataClassification", event.target.value)}><option>PUBLIC</option><option>INTERNAL</option><option>CONFIDENTIAL</option><option>RESTRICTED</option></select></L><L label="Approval policy"><input className={field} value={form.approvalPolicy} onChange={(event) => set("approvalPolicy", event.target.value)} /></L><L label="Retention policy"><select className={field} value={form.retention} onChange={(event) => set("retention", event.target.value)}><option value="7_days">7 days</option><option value="30_days">30 days</option><option value="90_days">90 days</option></select></L><L label="Maximum steps"><input className={field} type="number" min="1" max="100" value={form.maxSteps} onChange={(event) => set("maxSteps", event.target.value)} /></L><L label="Timeout seconds"><input className={field} type="number" min="1" max="3600" value={form.timeout} onChange={(event) => set("timeout", event.target.value)} /></L><L label="Test budget limit"><input className={field} type="number" min="0" step="0.01" value={form.costLimit} onChange={(event) => set("costLimit", event.target.value)} /></L><L label="Maximum tool risk"><select className={field} value={form.risk} onChange={(event) => set("risk", event.target.value)}><option value="read">Read-only</option><option value="write">Write with approval</option></select></L></div></div>; }
function Validation({ checks }) { return <div><h3 className="text-lg font-bold">Configuration validation</h3><p className="mt-1 text-sm text-stone-500">No external tool is executed during validation.</p><div className="mt-5 space-y-3">{checks.map((item) => <div key={item.label} className={`flex items-center justify-between rounded-xl border p-4 ${item.pass ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><span className="font-semibold">{item.label}</span><span className={`text-sm font-bold ${item.pass ? "text-emerald-700" : "text-amber-800"}`}>{item.pass ? "PASS" : "ACTION REQUIRED"}</span></div>)}</div></div>; }
function Review({ form, options, validation }) { return <div><h3 className="text-lg font-bold">Review draft</h3><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-stone-200 p-4"><dl className="space-y-3 text-sm">{[["Name", form.name], ["Category", form.category], ["Business owner", form.businessOwner], ["Technical owner", form.technicalOwner], ["Model", `${form.provider} · ${form.model}`], ["Tools", `${form.tools.length} selected`], ["Knowledge", `${form.knowledge.length} selected`], ["Classification", form.dataClassification]].map(([label, value]) => <div key={label} className="flex justify-between gap-4"><dt className="text-stone-500">{label}</dt><dd className="text-right font-semibold">{value || "Not provided"}</dd></div>)}</dl></div><div className="rounded-xl border border-stone-200 p-4"><h4 className="font-bold">Validation</h4><ul className="mt-3 space-y-2 text-sm">{validation.map((item) => <li key={item.label} className="flex items-center gap-2"><ShieldCheck size={15} className={item.pass ? "text-emerald-600" : "text-amber-600"} />{item.label}: {item.pass ? "Pass" : "Action required"}</li>)}</ul><p className="mt-4 text-xs text-stone-500">Saving creates a draft only. It does not publish the agent or grant additional permissions.</p></div></div><div className="sr-only">{options.models.length} governed models available.</div></div>; }
