import {ArrowLeft, ExternalLink, RefreshCw, Search, ShieldAlert} from "lucide-react";
import {Link, Navigate, useParams} from "react-router-dom";
import {useCapabilities, useIntegration, useIntegrationActions, useIntegrationOperations, useIntegrationUsage} from "../../hooks/useIntegrations";
import IntegrationHealthBadge from "../../components/integrations/IntegrationHealthBadge";

const tabs=["overview","configuration","authentication","mappings","synchronization","runs","data-quality","source-records","webhooks","access","activity"];
const panel="rounded-2xl border border-stone-300 bg-white p-5 shadow-sm";
export default function IntegrationDetailPage(){
  const {connectionId,tab,runId}=useParams(),active=runId?"runs":tab||"overview";
  const connection=useIntegration(connectionId),caps=useCapabilities(connectionId),usage=useIntegrationUsage(connectionId),operations=useIntegrationOperations(connectionId,active),actions=useIntegrationActions(connectionId);
  if(!tab&&!runId)return <Navigate replace to={`/integrations/${connectionId}/overview`}/>;
  if(!tabs.includes(active))return <Navigate replace to={`/integrations/${connectionId}/overview`}/>;
  if(connection.isLoading)return <main className="p-8">Loading integration…</main>;
  if(connection.isError||!connection.data)return <main className="min-h-full bg-[#faf8f5] p-8"><h1 className="font-display text-3xl font-bold">Integration not found</h1><p className="mt-2 text-stone-600">This integration is unavailable or outside your authorized tenant scope.</p></main>;
  const row=connection.data;
  const connectMicrosoft=async()=>{const result=await actions.connectMicrosoft.mutateAsync();window.location.assign(result.authorization_url)};
  return <main className="min-h-full bg-[#faf8f5] p-4 text-stone-900 md:p-8"><Link to="/integrations" className="inline-flex items-center gap-2 text-sm font-semibold text-stone-600"><ArrowLeft size={16}/>Integrations</Link><header className="mt-5 flex flex-wrap justify-between gap-4"><div><div className="flex flex-wrap items-center gap-3"><h1 className="font-display text-3xl font-bold">{row.display_name}</h1><IntegrationHealthBadge health={row.health_status}/></div><p className="mt-2 text-stone-600">{row.connector_type.replaceAll("_"," ")} · {safeHost(row.base_url)}</p></div><div className="flex flex-wrap gap-2">{row.connector_type==="outlook_calendar"&&<Action onClick={connectMicrosoft} icon={<ExternalLink size={15}/>} label={actions.connectMicrosoft.isPending?"Connecting…":"Connect Microsoft"}/>}<Action onClick={()=>actions.sync.mutate(row.id)} icon={<RefreshCw size={15}/>} label={actions.sync.isPending?"Synchronizing…":"Synchronize"}/><Action onClick={()=>actions.test.mutate(row.id)} icon={<RefreshCw size={15}/>} label="Test connection"/><button onClick={()=>actions.discover.mutate(row.id)} className="inline-flex items-center gap-2 rounded-xl bg-[#a00028] px-4 py-2 text-sm font-semibold text-white"><Search size={15}/>Discover capabilities</button></div></header><nav className="mt-6 flex overflow-x-auto border-b border-stone-300">{tabs.map(name=><Link key={name} to={`/integrations/${connectionId}/${name}`} className={`min-w-max border-b-2 px-3 py-3 text-sm font-semibold capitalize ${active===name?"border-[#a00028] text-[#a00028]":"border-transparent text-stone-500"}`}>{name.replaceAll("-"," ")}</Link>)}</nav><section className="mt-6">{operations.isLoading?<Panel title="Loading operational records…"/>:operations.isError?<Unavailable title="Operational data unavailable" detail="Apply the connector operations migration and retry."/>:<OperationalSection active={active} data={operations.data} row={row} capabilities={caps.data||[]} usage={usage.data}/>}</section></main>;
}
function OperationalSection({active,data,row,usage}){
  if(active==="overview")return <div className="grid gap-4 lg:grid-cols-2"><Panel title="Connector summary"><Data values={data.summary||{Status:row.status,Health:row.health_status}}/></Panel><Panel title="Operational usage"><Data values={{Mode:data.mode,Tools:row.tools_count||0,Actions:row.actions_count||0,Agents:row.agents_count||0,Requests:usage?.requests||0,Failures:usage?.failed||0,"Last synchronization":data.last_sync||"Never"}}/></Panel></div>;
  if(Array.isArray(data))return <Panel title={active.replaceAll("-"," ")}><Table rows={data}/></Panel>;
  if(active==="data-quality")return <div className="grid gap-4 lg:grid-cols-3"><Panel title="Quality score"><p className="text-5xl font-bold text-[#a00028]">{data.score}%</p><p className="mt-2 text-sm text-stone-500">Rules {data.rules_version}</p></Panel><Panel title="Record outcomes"><Data values={{Valid:data.valid_records,Quarantined:data.quarantined}}/></Panel><Panel title="Quarantine"><Table rows={data.quarantine||[]}/></Panel></div>;
  if(active==="authentication")return <Panel title="Authentication and permissions"><Data values={{Status:data.status,"Authentication type":data.auth_type,"Credential reference":data.credential_configured?"Configured — value hidden":"Not configured","Granted scopes":data.granted_scopes?.join(", "),"Missing scopes":data.missing_scopes?.join(", ")||"None","Secret returned":data.secret_value_returned?"Yes":"No"}}/></Panel>;
  const values={};Object.entries(data||{}).forEach(([key,value])=>{values[key.replaceAll("_"," ")]=typeof value==="object"?JSON.stringify(value):value});
  return <Panel title={active.replaceAll("-"," ")}><Data values={values}/>{active==="access"&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Every outbound operation remains blocked behind Approval and Action Center review.</p>}</Panel>;
}
function Table({rows}){if(!rows?.length)return <p className="text-sm text-stone-500">No records yet. Run synchronization to populate this section.</p>;const columns=Object.keys(rows[0]).slice(0,6);return <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b border-stone-300">{columns.map(column=><th className="px-3 py-2 capitalize text-stone-500" key={column}>{column.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr className="border-b border-stone-100" key={row.id||index}>{columns.map(column=><td className="max-w-xs truncate px-3 py-3" key={column}>{typeof row[column]==="object"?JSON.stringify(row[column]):String(row[column]??"—")}</td>)}</tr>)}</tbody></table></div>}
function Action({onClick,icon,label}){return <button onClick={onClick} className="inline-flex items-center gap-2 rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm font-semibold">{icon}{label}</button>}
function Unavailable({title,detail}){return <article className={`${panel} border-amber-200 bg-amber-50`}><ShieldAlert className="text-amber-700"/><h2 className="mt-3 text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-amber-900">{detail}</p></article>}
function Panel({title,children}){return <article className={panel}><h2 className="capitalize text-xl font-bold">{title}</h2><div className="mt-4">{children}</div></article>}
function Data({values}){return <dl className="divide-y divide-stone-200 text-sm">{Object.entries(values||{}).map(([label,value])=><div className="flex justify-between gap-4 py-3" key={label}><dt className="capitalize text-stone-500">{label}</dt><dd className="max-w-[65%] break-words text-right font-semibold">{String(value??"—")}</dd></div>)}</dl>}
function safeHost(value){try{return new URL(value).hostname}catch{return "Endpoint not configured"}}
