import { ExternalLink, MessageSquareText, ShieldCheck, X } from "lucide-react";
import { useState } from "react";

const nextStatus={IDENTIFIED:"ASSESSED",ASSESSED:"OPEN",OPEN:"MITIGATING",MITIGATING:"CLOSED",INVESTIGATING:"RESOLVING",RESOLVING:"RESOLVED",ACKNOWLEDGED:"IN_PROGRESS",IN_PROGRESS:"RESOLVED",PROPOSED:"UNDER_REVIEW",UNDER_REVIEW:"PENDING",PENDING:"APPROVED",APPROVED:"IMPLEMENTED",BLOCKED:"IN_PROGRESS",OVERDUE:"COMPLETED"};

export default function RAIDItemDrawer({detail,loading,error,onClose,onReview,onTransition,onPropose,busy}) {
  const [note,setNote]=useState("");
  const [mode,setMode]=useState("overview");
  const item=detail?.item;
  const relationships=Array.isArray(detail?.relationships)?detail.relationships:[];
  const evidence=Array.isArray(detail?.evidence)?detail.evidence:[];
  const history=Array.isArray(detail?.history)?detail.history:[];
  const proposals=Array.isArray(detail?.proposals)?detail.proposals:[];
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/40" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}>
    <section role="dialog" aria-modal="true" aria-labelledby="raid-detail-title" className="h-full w-full max-w-2xl overflow-auto bg-[#faf8f5] shadow-2xl">
      <header className="sticky top-0 z-10 flex items-start justify-between border-b border-stone-300 bg-white p-5"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#a00028]">{item?.itemType||"RAID item"}</p><h2 id="raid-detail-title" className="font-display mt-1 text-2xl font-bold">{item?.reference||"Loading item…"}</h2></div><button autoFocus onClick={onClose} aria-label="Close RAID item" className="p-2 focus:ring-2 focus:ring-[#e0301e]"><X/></button></header>
      {loading&&<div role="status" className="p-8">Loading persisted RAID details…</div>}
      {error&&<div role="alert" className="m-5 border-l-4 border-red-600 bg-white p-4 text-red-800">{error}</div>}
      {item&&<div className="p-5">
        <h3 className="font-display text-2xl font-bold">{item.name}</h3><p className="mt-3 leading-7 text-stone-700">{item.description}</p>
        <dl className="mt-6 grid gap-4 border-y border-stone-300 py-5 sm:grid-cols-3"><Fact label="Status" value={item.status}/><Fact label="Exposure" value={item.residualExposureBand||item.exposureBand||"UNKNOWN"}/><Fact label="Score" value={item.residualExposureScore??item.exposureScore??"Unknown"}/><Fact label="Owner" value={item.ownerId||item.validationOwnerId||item.decisionOwnerId||"Unassigned"}/><Fact label="Due / review" value={item.dueDate||item.reviewDate||item.validationDueDate||"Not set"}/><Fact label="Age" value={`${item.ageDays} days`}/><Fact label="Source" value="Persisted record"/><Fact label="Evidence" value={`${item.evidenceCount} linked`}/><Fact label="Relationships" value={`${relationships.length} linked`}/><Fact label="Version" value={item.version}/></dl>
        <div className="mt-5 flex flex-wrap gap-2" role="group" aria-label="RAID actions"><button onClick={()=>setMode("review")} className="border border-stone-400 bg-white px-3 py-2 text-sm font-semibold">Add review note</button>{nextStatus[item.status]&&<button disabled={busy} onClick={()=>onTransition(item,nextStatus[item.status])} className="border border-stone-400 bg-white px-3 py-2 text-sm font-semibold">Move to {nextStatus[item.status].replaceAll("_"," ")}</button>}<button onClick={()=>setMode("proposal")} className="bg-[#e0301e] px-3 py-2 text-sm font-semibold text-white">Propose intervention</button>{item.dependencyId&&<a href={`/dependencies/${encodeURIComponent(item.dependencyId)}?view=graph`} className="border border-stone-400 bg-white px-3 py-2 text-sm font-semibold">Open dependency graph</a>}<a href={`/copilot?raid=${encodeURIComponent(item.id)}`} className="inline-flex items-center gap-2 border border-stone-400 bg-white px-3 py-2 text-sm font-semibold">Ask Axiom <MessageSquareText size={15}/></a></div>
        {mode==="review"&&<form onSubmit={event=>{event.preventDefault();onReview(item,note);setNote("");setMode("overview")}} className="mt-5 border border-stone-300 bg-white p-4"><label className="block text-sm font-semibold">Review note<textarea required value={note} onChange={event=>setNote(event.target.value)} className="mt-2 min-h-28 w-full border border-stone-300 p-3 font-normal"/></label><button disabled={busy} className="mt-3 bg-[#202020] px-4 py-2 text-sm font-semibold text-white">Save review</button></form>}
        {mode==="proposal"&&<form onSubmit={event=>{event.preventDefault();onPropose(item,note);setNote("");setMode("overview")}} className="mt-5 border border-[#e0301e] bg-white p-4"><label className="block text-sm font-semibold">Draft intervention<textarea required value={note} onChange={event=>setNote(event.target.value)} className="mt-2 min-h-28 w-full border border-stone-300 p-3 font-normal"/></label><button disabled={busy} className="mt-3 bg-[#e0301e] px-4 py-2 text-sm font-semibold text-white">Save as proposed</button><p className="mt-2 text-xs text-stone-500">Internal proposal only. Nothing is executed externally.</p></form>}
        <section className="mt-7" aria-labelledby="detail-relationships-title"><h3 id="detail-relationships-title" className="font-display text-xl font-bold">Relationships</h3>{relationships.length?<ul className="mt-3 space-y-2">{relationships.map(relationship=><li key={relationship.id} className="border border-stone-300 bg-white p-3 text-sm"><strong>{relationship.relationshipType.replaceAll("_"," ")}</strong><span className="ml-2 text-stone-600">{relationship.entityType} · {relationship.entityId}</span></li>)}</ul>:<p className="mt-2 text-sm text-stone-500">No additional typed relationships are linked.</p>}</section>
        <section className="mt-7" aria-labelledby="detail-evidence-title"><h3 id="detail-evidence-title" className="font-display text-xl font-bold">Evidence</h3>{evidence.length?<ul className="mt-3 space-y-3">{evidence.map(evidenceItem=><li key={evidenceItem.id} className="border border-stone-300 bg-white p-4"><div className="flex justify-between gap-3"><strong>{evidenceItem.title}</strong>{evidenceItem.sourceUrl&&<a href={evidenceItem.sourceUrl} target="_blank" rel="noreferrer" aria-label={`Open source for ${evidenceItem.title}`}><ExternalLink size={16}/></a>}</div><p className="mt-1 text-sm text-stone-600">{evidenceItem.summary||"No source excerpt stored."}</p><p className="mt-2 text-xs text-stone-500">{evidenceItem.sourceType} · {evidenceItem.sourceSystem}</p></li>)}</ul>:<p className="mt-2 text-sm text-stone-500">No authorized evidence is linked.</p>}</section>
        <section className="mt-7" aria-labelledby="detail-history-title"><h3 id="detail-history-title" className="font-display text-xl font-bold">Activity history</h3><ol className="mt-3 space-y-3">{history.map(historyItem=><li key={historyItem.id} className="border-l-2 border-stone-300 pl-4"><strong className="text-sm">{historyItem.eventType.replaceAll("_"," ")}</strong><p className="text-xs text-stone-500">{new Date(historyItem.changedAt).toLocaleString()} · {historyItem.actorId}</p>{historyItem.note&&<p className="mt-1 text-sm">{historyItem.note}</p>}</li>)}</ol></section>
        {proposals.length>0&&<section className="mt-7 border-t border-stone-300 pt-5"><h3 className="flex items-center gap-2 font-display text-xl font-bold"><ShieldCheck size={19}/>Proposed interventions</h3>{proposals.map(proposal=><article key={proposal.id} className="mt-3 border border-stone-300 bg-white p-4"><strong>{proposal.actionType.replaceAll("_"," ")}</strong><p className="mt-1 text-sm">{proposal.content}</p><p className="mt-2 text-xs text-stone-500">{proposal.status} · approval required</p></article>)}</section>}
      </div>}
    </section>
  </div>;
}

function Fact({label,value}){return <div><dt className="text-xs uppercase tracking-wider text-stone-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
