import type { RuntimeEvent, RuntimeStatus } from "../types/runtime";

export type ActivityState = "pending" | "running" | "completed" | "waiting" | "failed" | "cancelled" | "skipped";
export type RuntimeActivityItem = { id:string; label:string; state:ActivityState; sequence:number; durationMs?:number; timestamp?:string; important:boolean };
const terminal = new Set<RuntimeStatus>(["COMPLETED", "FAILED", "CANCELLED", "TIMED_OUT"]);
const normalized = (value?:string) => String(value || "").toLowerCase().replaceAll("_", " ").replaceAll(".", " ");
const countFrom = (event:RuntimeEvent) => { const result=event.result_summary as Record<string,unknown>|undefined; const direct=[result?.project_count,result?.evidence_count,result?.count].find(value=>typeof value==="number"); if(typeof direct==="number")return direct; const collection=[result?.projects,result?.values,result?.issues,result?.records].find(Array.isArray); return Array.isArray(collection)?collection.length:undefined; };
export function activityState(event:RuntimeEvent):ActivityState { const value=normalized(event.status || event.aggregate_status); if(value.includes("fail")||value.includes("error")||value.includes("timed out"))return "failed"; if(value.includes("cancel"))return "cancelled"; if(value.includes("wait")||event.type==="required_input"||event.type==="approval_required")return "waiting"; if(value.includes("complete")||value.includes("success"))return "completed"; if(value.includes("skip"))return "skipped"; if(value.includes("run")||value.includes("start")||value.includes("progress"))return "running"; return "pending"; }
export function safeActivityLabel(event:RuntimeEvent):string { const value=normalized(`${event.type} ${event.name}`); const state=activityState(event); const done=state==="completed"; if(event.type==="approval_required")return "Waiting for approval"; if(event.type==="required_input")return "Waiting for the required information"; if(value.includes("request received")||value.includes("runtime started"))return done?"Understood the request":"Understanding your request…"; if(value.includes("context")&&(value.includes("author")||value.includes("resolv")))return done?"Delivery context authorized":"Checking delivery access…"; if(value.includes("agent")&&(value.includes("select")||value.includes("rout")))return event.agent?`Selected ${event.agent}`:(done?"Delivery agent selected":"Selecting the delivery agent…"); if(value.includes("planner")||value.includes("planning"))return done?"Analysis plan prepared":"Planning the required analysis…"; if(value.includes("intent"))return done?"Understood the request":"Understanding your request…"; if(value.includes("parameter"))return done?"Request details checked":"Checking the request details…"; if(value.includes("knowledge")||value.includes("evidence")){const count=countFrom(event);return done?(count==null?"Supporting evidence reviewed":`Found ${count} supporting records`):"Retrieving authorized evidence…";} if(value.includes("jira")&&value.includes("project")){const count=countFrom(event);return done?(count==null?"Jira projects retrieved":`Retrieved ${count} Jira projects`):"Retrieving Jira projects…";} if(value.includes("tool")||event.type.startsWith("tool_"))return done?"Delivery data retrieved":"Retrieving delivery data…"; if(value.includes("action")||event.type.startsWith("action_"))return done?"Governed action prepared":"Preparing the governed action…"; if(value.includes("response")||value.includes("result generated"))return done?"Response prepared":"Preparing the response…"; if(value.includes("usage")||value.includes("metric"))return "Usage recorded"; if(state==="failed")return value.includes("jira")?"Jira could not be reached":"Analysis could not be completed"; if(state==="cancelled")return "Execution cancelled"; if(event.aggregate_status==="COMPLETED"||value.includes("completed"))return "Analysis completed"; return state==="running"?"Working on your request…":"Runtime activity recorded"; }
export function runtimeActivity(events:RuntimeEvent[]=[], status?:RuntimeStatus):RuntimeActivityItem[] { const byId=new Map<string,RuntimeEvent>(); [...events].sort((a,b)=>(a.sequence||0)-(b.sequence||0)).forEach(event=>{const id=String(event.step_id||event.component_id||event.tool_execution_id||event.action_execution_id||event.event_id||`${event.type}:${event.name||"event"}`);byId.set(id,{...(byId.get(id)||{}),...event});}); const items=[...byId.entries()].map(([id,event])=>{const state=activityState(event);return {id,label:safeActivityLabel(event),state,sequence:event.sequence||0,durationMs:event.duration_ms,timestamp:event.timestamp,important:["waiting","failed","cancelled"].includes(state)||event.type==="approval_required"||event.type==="required_input"};}); const deduped=items.filter((item,index)=>items.findIndex(candidate=>candidate.label===item.label&&candidate.state===item.state)===index); if(status&&terminal.has(status))return deduped.map(item=>item.state==="running"?{...item,state:"completed"}:item); return deduped; }
