import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";
import DependencyIntelligencePage from "./DependencyIntelligencePage";

const item={id:"dep-18",reference:"D-018",name:"Customer API delivery",description:"Synthetic provider delivery",dependencyType:"TECHNICAL",relationshipType:"DEPENDS_ON",status:"BLOCKED",health:{score:35,status:"RED",dataCompleteness:1,limitations:[],definitionVersion:"v1"},priority:{score:100,band:"CRITICAL",triggeredFactors:[{factor:"Currently blocked",points:25}],affectedEntities:["SPRINT:s24","RELEASE:r4"],ruleVersion:"v1"},impact:"CRITICAL",ownerId:"owner-1",providerOwnerId:"provider-1",provider:{key:"SYSTEM:customer-api",entityType:"SYSTEM",entityId:"customer-api",name:"Customer API"},consumer:{key:"WORK_ITEM:mobile",entityType:"WORK_ITEM",entityId:"mobile",name:"Mobile App"},requiredByDate:"2026-08-18",forecastResolutionDate:"2026-08-23",identifiedAt:"2026-08-01T00:00:00Z",criticalPath:true,external:true,sourceSystem:"MANUAL",projectId:"project-1",ageDays:14,evidenceCount:1,downstreamCount:2,version:1,updatedAt:"2026-08-15T00:00:00Z"};
const mocks=vi.hoisted(()=>({getDependencies:vi.fn(),getDependencySummary:vi.fn(),getDependencyGraph:vi.fn(),getCriticalPaths:vi.fn(),getBottlenecks:vi.fn(),getDetectedDependencies:vi.fn(),getDependencyDetail:vi.fn(),createDependency:vi.fn(),acknowledgeDependency:vi.fn(),transitionDependency:vi.fn(),runDependencyScenario:vi.fn(),createDependencyProposal:vi.fn(),dismissDependencyCandidate:vi.fn()}));
vi.mock("../../services/dependency.service",()=>mocks);
function setup(path="/dependencies"){return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/dependencies" element={<DependencyIntelligencePage/>}/><Route path="/dependencies/:dependencyId" element={<DependencyIntelligencePage/>}/></Routes></MemoryRouter>)}
beforeEach(()=>{Object.values(mocks).forEach(mock=>mock.mockReset());mocks.getDependencies.mockResolvedValue({items:[item],page:1,pageSize:20,total:1,pages:1,generatedAt:"2026-08-15T00:00:00Z",source:"persisted"});mocks.getDependencySummary.mockResolvedValue({criticalDependencies:1,atRiskDependencies:0,blockedDependencies:1,overdueDependencies:0,unownedDependencies:0,criticalPaths:1,generatedAt:"2026-08-15T00:00:00Z",source:"persisted"});mocks.getDependencyGraph.mockResolvedValue({nodes:[{id:"SYSTEM:customer-api",entityType:"SYSTEM",entityId:"customer-api",name:"Customer API",upstreamCount:0,downstreamCount:1},{id:"WORK_ITEM:mobile",entityType:"WORK_ITEM",entityId:"mobile",name:"Mobile App",upstreamCount:1,downstreamCount:0}],edges:[{id:"dep-18",reference:"D-018",source:"SYSTEM:customer-api",target:"WORK_ITEM:mobile",relationshipType:"DEPENDS_ON",status:"BLOCKED",criticalPath:true}],nodeCount:2,edgeCount:1});mocks.getCriticalPaths.mockResolvedValue({items:[{id:"CP-001",classification:"POTENTIAL_CRITICAL_PATH",nodes:["SYSTEM:customer-api","WORK_ITEM:mobile"],pathLength:1,currentDelayDays:5,dataCompleteness:.5,limitations:["Incomplete timing data"]}]});mocks.getBottlenecks.mockResolvedValue({items:[]});mocks.getDetectedDependencies.mockResolvedValue({items:[]});mocks.getDependencyDetail.mockResolvedValue({item,evidence:[{id:"ev-1",title:"Provider status",sourceType:"STATUS_UPDATE",sourceSystem:"MANUAL",capturedAt:"2026-08-15T00:00:00Z"}],history:[],proposals:[],upstream:[],downstream:[{id:"SPRINT:s24",depth:1}],recommendationDrafts:[],scenarios:[],relatedRAID:[],externalWrites:false});mocks.runDependencyScenario.mockResolvedValue({changeValue:{days:5},scenarioResult:{directlyAffectedEntities:["SPRINT:s24"],indirectlyAffectedEntities:["RELEASE:r4"],affectedSprints:["s24"],affectedReleases:["r4"]},authoritativeRecordsChanged:false});mocks.createDependencyProposal.mockResolvedValue({externalWrites:false});});

describe("Dependency Intelligence",()=>{
  it("loads persisted summary, register, accessible graph and URL detail",async()=>{setup();expect(await screen.findByText(/Customer API delivery/)).toBeInTheDocument();expect(screen.getByRole("button",{name:/Critical dependencies/})).toHaveTextContent("1");fireEvent.click(screen.getByRole("tab",{name:"Register"}));fireEvent.click((await screen.findAllByRole("button",{name:"D-018"}))[0]);expect(await screen.findByRole("dialog",{name:"D-018"})).toBeInTheDocument();expect(screen.getByText("0 upstream · 1 downstream authorized entities")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Close dependency details"}));fireEvent.click(screen.getByRole("tab",{name:"Graph"}));expect(await screen.findByRole("heading",{name:"Accessible relationship view"})).toBeInTheDocument();expect(screen.getByText(/BLOCKED · Critical path/)).toBeInTheDocument();});
  it("runs a read-only five-day impact scenario",async()=>{setup();await screen.findByText(/Customer API delivery/);fireEvent.click(screen.getByRole("tab",{name:"Impact Analysis"}));fireEvent.change(screen.getByLabelText("Dependency"),{target:{value:"dep-18"}});fireEvent.click(screen.getByRole("button",{name:"Run scenario"}));await waitFor(()=>expect(mocks.runDependencyScenario).toHaveBeenCalledWith("dep-18",5,false));expect(await screen.findByText(/authoritative records changed: false/)).toBeInTheDocument();});
  it("tolerates omitted optional response collections",async()=>{mocks.getDependencies.mockResolvedValueOnce({page:1,pageSize:20,total:0,pages:0});mocks.getDependencyGraph.mockResolvedValueOnce({});mocks.getCriticalPaths.mockResolvedValueOnce({});mocks.getBottlenecks.mockResolvedValueOnce({});mocks.getDetectedDependencies.mockResolvedValueOnce({});mocks.getDependencyDetail.mockResolvedValueOnce({item});setup("/dependencies/dep-18");expect(await screen.findByRole("dialog",{name:"D-018"})).toBeInTheDocument();expect(screen.getByText("No authorized evidence is linked.")).toBeInTheDocument();expect(screen.getByText("No persisted history is available.")).toBeInTheDocument();});
});
