import { useState } from "react";
import { ArrowRight, Search } from "lucide-react";
import StatusBadge from "./StatusBadge";
export default function AttentionRequiredPanel({ items, onSelect }) {
  const [query,setQuery]=useState(""); const [type,setType]=useState("All"); const filtered=items.filter(i=>(type==="All"||i.type===type)&&`${i.item} ${i.owner}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm" aria-labelledby="attention-title"><div className="border-b border-slate-200 p-5 lg:p-6"><h2 id="attention-title" className="text-lg font-semibold text-slate-950">Attention Required</h2><p className="mt-1 text-sm text-slate-500">Items that may affect delivery outcomes</p></div>
    <div className="flex flex-wrap gap-3 border-b border-slate-100 p-4"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><span className="sr-only">Search attention items</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search item or owner" className="w-full border border-slate-300 py-2 pl-9 pr-3 text-sm"/></label><select aria-label="Filter attention type" value={type} onChange={e=>setType(e.target.value)} className="border border-slate-300 px-3 text-sm"><option>All</option><option>Risk</option><option>Action</option><option>Dependency</option></select></div>
    {filtered.length === 0 ? <div className="p-10 text-center"><p className="font-medium text-slate-800">You’re all caught up</p><p className="mt-1 text-sm text-slate-500">No delivery items match the current filters.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Item","Type","Impact","Status","Owner","Due date","Action"].map((h)=><th key={h} scope="col" className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item)=><tr key={item.id} className="hover:bg-slate-50"><th scope="row" className="px-5 py-4 font-semibold text-slate-900">{item.item}{item.score&&<span className="ml-2 text-xs font-normal text-slate-400">Score {item.score}</span>}</th><td className="px-5 py-4 text-slate-600">{item.type}</td><td className="px-5 py-4"><StatusBadge>{item.impact}</StatusBadge></td><td className="px-5 py-4"><StatusBadge>{item.status}</StatusBadge></td><td className="px-5 py-4 text-slate-600">{item.owner}</td><td className="px-5 py-4 text-slate-600"><time dateTime={item.dueDate}>{new Date(`${item.dueDate}T00:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time></td><td className="px-5 py-4"><button type="button" onClick={()=>onSelect(item)} className="inline-flex items-center gap-1 font-semibold text-blue-700 hover:text-blue-900 focus:outline-none focus:ring-2 focus:ring-blue-600">{item.status === "Overdue" ? "Take action" : "View"}<ArrowRight className="h-4 w-4"/></button></td></tr>)}</tbody></table></div>}
  </section>;
}
