import { useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
export default function DeliveryTrendChart({ data }) {
  const [periods, setPeriods] = useState("12");
  const [shown,setShown]=useState({portfolioHealth:true,sprintPredictability:true,commitmentAchievement:true});
  const visible = data.slice(-Number(periods));
  const first=visible[0],last=visible.at(-1); const summary=first&&last?`Across ${visible.length} periods, portfolio health moved ${last.portfolioHealth-first.portfolioHealth} points, sprint predictability moved ${last.sprintPredictability-first.sprintPredictability} points, and scope completion moved ${last.commitmentAchievement-first.commitmentAchievement} points.`:"No trend data available.";
  return <section className="border border-stone-300 bg-white p-5 lg:p-6" aria-labelledby="delivery-trend-title">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 id="delivery-trend-title" className="font-display text-xl font-bold text-[#202020]">Delivery Trend</h2><p className="mt-1 text-sm text-stone-500">Performance across recent reporting periods</p></div><label className="text-sm font-medium text-stone-600">Period <select aria-label="Reporting periods" value={periods} onChange={(e)=>setPeriods(e.target.value)} className="ml-2 border border-stone-300 bg-white px-3 py-2 text-stone-800 focus:outline-none focus:ring-2 focus:ring-[#e0301e]"><option value="12">Last 12 weeks</option><option value="8">Last 8 weeks</option><option value="4">Last 4 weeks</option></select></label></div>
    <fieldset className="mb-3 flex flex-wrap gap-4 text-xs"><legend className="sr-only">Visible trend series</legend>{[["portfolioHealth","Plan Commitment"],["sprintPredictability","Delivery Performance"],["commitmentAchievement","Scope Completed"]].map(([key,label])=><label key={key} className="flex items-center gap-2"><input type="checkbox" checked={shown[key]} onChange={()=>setShown(v=>({...v,[key]:!v[key]}))}/>{label}</label>)}</fieldset>
    <div className="h-72 w-full" role="img" aria-label={summary}><ResponsiveContainer><LineChart data={visible} margin={{ top: 8, right: 12, left: -20, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#ded9d3" vertical={false}/><XAxis dataKey="period" tick={{fill:"#5c5752",fontSize:12}} axisLine={false} tickLine={false}/><YAxis domain={[0,100]} tick={{fill:"#5c5752",fontSize:12}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:0,border:"1px solid #ded9d3"}}/><Legend wrapperStyle={{fontSize:12,paddingTop:16}}/>{shown.portfolioHealth&&<Line type="monotone" name="Plan Commitment" dataKey="portfolioHealth" stroke="#a00028" strokeWidth={3} dot={false}/>} {shown.sprintPredictability&&<Line type="monotone" name="Delivery Performance" dataKey="sprintPredictability" stroke="#e0301e" strokeWidth={3} dot={false}/>} {shown.commitmentAchievement&&<Line type="monotone" name="Scope Completed" dataKey="commitmentAchievement" stroke="#d98b00" strokeWidth={3} dot={false}/>}</LineChart></ResponsiveContainer></div><p className="mt-3 text-xs leading-5 text-stone-500">{summary}</p>
  </section>;
}
