import type {PortfolioWorkspace,Programme,Project} from "../../services/portfolio.service";

const generatedAt="2026-08-20T14:30:00Z";
const programmes:Programme[]=[
  {id:"prog-digital",portfolioId:"portfolio-enterprise",name:"Digital Customer Experience",description:"Modernise customer onboarding, servicing, and digital engagement.",status:"ACTIVE",health:{score:74,status:"AMBER"},confidence:82,sponsor:"Maya Chen",manager:"Omar Ali",strategicTheme:"Customer growth",approvedBudget:"12500000.00",actualSpend:"7800000.00",forecast:"13100000.00",currency:"GBP",activeProjects:2,atRiskProjects:1,criticalRaid:2,overdueDependencies:2,updatedAt:"2026-08-20T12:10:00Z"},
  {id:"prog-data",portfolioId:"portfolio-enterprise",name:"Data & AI Enablement",description:"Establish governed data products and responsible AI capabilities.",status:"ACTIVE",health:{score:86,status:"GREEN"},confidence:89,sponsor:"Sara Nabil",manager:"Daniel Okafor",strategicTheme:"Operational intelligence",approvedBudget:"9200000.00",actualSpend:"5100000.00",forecast:"9000000.00",currency:"GBP",activeProjects:2,atRiskProjects:0,criticalRaid:1,overdueDependencies:0,updatedAt:"2026-08-20T11:45:00Z"},
  {id:"prog-core",portfolioId:"portfolio-enterprise",name:"Core Platform Renewal",description:"Reduce legacy risk while improving resilience and delivery speed.",status:"AT_RISK",health:{score:48,status:"RED"},confidence:71,sponsor:"James Wilson",manager:"Priya Raman",strategicTheme:"Resilient foundations",approvedBudget:"15800000.00",actualSpend:"11200000.00",forecast:"17400000.00",currency:"GBP",activeProjects:2,atRiskProjects:2,criticalRaid:4,overdueDependencies:3,updatedAt:"2026-08-20T10:20:00Z"},
];
const projects:Project[]=[
  {id:"project-onboarding",programmeId:"prog-digital",name:"Customer Onboarding",programme:"Digital Customer Experience",description:"Deliver a faster, evidence-led onboarding journey across digital channels.",status:"AT_RISK",health:{score:55,status:"RED"},confidence:76,manager:"Layla Hassan",strategicTheme:"Customer growth",approvedBudget:"6800000.00",actualSpend:"4400000.00",forecast:"7350000.00",currency:"GBP",criticalRaid:2,overdueDependencies:2,milestones:4,nextRelease:"2026-09-12",evidenceCount:18,updatedAt:"2026-08-20T12:00:00Z"},
  {id:"project-self-service",programmeId:"prog-digital",name:"Digital Self-Service",programme:"Digital Customer Experience",description:"Expand authenticated self-service and reduce avoidable contact.",status:"ACTIVE",health:{score:88,status:"GREEN"},confidence:91,manager:"Noah Mensah",strategicTheme:"Customer growth",approvedBudget:"5700000.00",actualSpend:"3400000.00",forecast:"5750000.00",currency:"GBP",criticalRaid:0,overdueDependencies:0,milestones:3,nextRelease:"2026-09-28",evidenceCount:24,updatedAt:"2026-08-20T11:15:00Z"},
  {id:"project-data-products",programmeId:"prog-data",name:"Enterprise Data Products",programme:"Data & AI Enablement",description:"Publish trusted reusable customer and operations data products.",status:"ACTIVE",health:{score:84,status:"GREEN"},confidence:88,manager:"Aisha Bello",strategicTheme:"Operational intelligence",approvedBudget:"5100000.00",actualSpend:"2900000.00",forecast:"5000000.00",currency:"GBP",criticalRaid:1,overdueDependencies:0,milestones:3,nextRelease:"2026-10-04",evidenceCount:31,updatedAt:"2026-08-20T09:45:00Z"},
  {id:"project-ai-governance",programmeId:"prog-data",name:"Responsible AI Controls",programme:"Data & AI Enablement",description:"Operationalise model governance, evaluation, and cost controls.",status:"ACTIVE",health:{score:90,status:"GREEN"},confidence:93,manager:"Youssef Karim",strategicTheme:"Operational intelligence",approvedBudget:"4100000.00",actualSpend:"2200000.00",forecast:"4000000.00",currency:"GBP",criticalRaid:0,overdueDependencies:0,milestones:2,nextRelease:"2026-09-20",evidenceCount:38,updatedAt:"2026-08-20T13:05:00Z"},
  {id:"project-payments",programmeId:"prog-core",name:"Payments Modernisation",programme:"Core Platform Renewal",description:"Replace the legacy payment gateway and strengthen operational resilience.",status:"BLOCKED",health:{score:28,status:"RED"},confidence:64,manager:"Amira Saleh",strategicTheme:"Resilient foundations",approvedBudget:"8900000.00",actualSpend:"6900000.00",forecast:"10100000.00",currency:"GBP",criticalRaid:3,overdueDependencies:2,milestones:5,nextRelease:"2026-09-05",evidenceCount:12,updatedAt:"2026-08-20T10:10:00Z"},
  {id:"project-cloud",programmeId:"prog-core",name:"Cloud Foundation",programme:"Core Platform Renewal",description:"Create compliant landing zones and migrate priority shared services.",status:"AT_RISK",health:{score:58,status:"RED"},confidence:75,manager:"Thomas Reed",strategicTheme:"Resilient foundations",approvedBudget:"6900000.00",actualSpend:"4300000.00",forecast:"7300000.00",currency:"GBP",criticalRaid:1,overdueDependencies:1,milestones:4,nextRelease:"2026-10-15",evidenceCount:20,updatedAt:"2026-08-20T08:30:00Z"},
];

export const mockPortfolioWorkspace:PortfolioWorkspace={
  sprints:[],releases:[],workItems:[],
  generatedAt,source:"Development demonstration fixture",freshness:"Demo snapshot · 20 Aug 2026 14:30 UTC",
  portfolios:[{id:"portfolio-enterprise",name:"Enterprise Change Portfolio",status:"ACTIVE",updatedAt:generatedAt}],
  health:{score:72.4,status:"AMBER",partial:false,version:"portfolio-health-v1",factors:{project:67.2,release:76,risk:65,dependency:70,milestone:81},weights:{project:.25,release:.25,risk:.2,dependency:.15,milestone:.15}},
  programmes,projects,
  outcomes:[
    {id:"outcome-growth",portfolioId:"portfolio-enterprise",name:"Reduce digital onboarding abandonment",status:"AT_RISK",targetValue:"18",currentValue:"24",unit:"%",targetDate:"2026-12-31",confidence:76,owner:"Maya Chen",links:[{entityType:"PROGRAMME",entityId:"prog-digital",contribution:100}],updatedAt:generatedAt},
    {id:"outcome-resilience",portfolioId:"portfolio-enterprise",name:"Improve critical platform availability",status:"ACTIVE",targetValue:"99.99",currentValue:"99.92",unit:"%",targetDate:"2027-03-31",confidence:82,owner:"James Wilson",links:[{entityType:"PROJECT",entityId:"project-payments",contribution:55},{entityType:"PROJECT",entityId:"project-cloud",contribution:45}],updatedAt:generatedAt},
  ],
  milestones:[
    {id:"ms-1",name:"Onboarding UAT exit",projectId:"project-onboarding",project:"Customer Onboarding",status:"AT_RISK",baselineDate:"2026-08-25",forecastDate:"2026-09-03",actualDate:null,varianceDays:9,critical:true,owner:"Omar Ali",updatedAt:"2026-08-20T12:00:00Z"},
    {id:"ms-2",name:"Payment provider certification",projectId:"project-payments",project:"Payments Modernisation",status:"BLOCKED",baselineDate:"2026-08-18",forecastDate:"2026-09-08",actualDate:null,varianceDays:21,critical:true,owner:"Amira Saleh",updatedAt:"2026-08-20T10:10:00Z"},
    {id:"ms-3",name:"Customer data product v1",projectId:"project-data-products",project:"Enterprise Data Products",status:"ACTIVE",baselineDate:"2026-09-15",forecastDate:"2026-09-15",actualDate:null,varianceDays:0,critical:true,owner:"Aisha Bello",updatedAt:"2026-08-20T09:45:00Z"},
    {id:"ms-4",name:"AI control framework rollout",projectId:"project-ai-governance",project:"Responsible AI Controls",status:"ACTIVE",baselineDate:"2026-09-20",forecastDate:"2026-09-18",actualDate:null,varianceDays:-2,critical:false,owner:"Youssef Karim",updatedAt:"2026-08-20T13:05:00Z"},
    {id:"ms-5",name:"Landing zone wave 2",projectId:"project-cloud",project:"Cloud Foundation",status:"AT_RISK",baselineDate:"2026-09-30",forecastDate:"2026-10-10",actualDate:null,varianceDays:10,critical:true,owner:"Thomas Reed",updatedAt:"2026-08-20T08:30:00Z"},
  ],
  attention:[
    {id:"att-payment",kind:"Dependency",title:"Payment provider certification is blocking release validation",severity:"CRITICAL",score:95,entity:"Payments Modernisation",owner:"Amira Saleh",dueDate:"2026-08-18",explanation:{impact:35,urgency:25,critical_path:25,age:10},projectId:"project-payments"},
    {id:"att-uat",kind:"Milestone",title:"Onboarding UAT exit forecast slipped by nine days",severity:"HIGH",score:78,entity:"Customer Onboarding",owner:"Omar Ali",dueDate:"2026-08-25",explanation:{impact:21,urgency:25,critical_path:25,age:5},projectId:"project-onboarding"},
    {id:"att-budget",kind:"Investment",title:"Core Platform forecast exceeds approved budget",severity:"HIGH",score:72,entity:"Core Platform Renewal",owner:"Priya Raman",dueDate:null,explanation:{impact:35,urgency:15,critical_path:12,age:10},projectId:"project-payments"},
    {id:"att-evidence",kind:"Evidence",title:"Payments evidence coverage is below the portfolio threshold",severity:"MEDIUM",score:52,entity:"Payments Modernisation",owner:"Amira Saleh",dueDate:"2026-08-22",explanation:{impact:21,urgency:15,critical_path:11,age:5},projectId:"project-payments"},
  ],
  insights:[
    {id:"ins-payment",finding:"Payment modernisation risk is concentrated around one critical provider dependency.",severity:"CRITICAL",confidence:"High · 92%",explanation:"The dependency is overdue, critical-path, and linked to the next release and certification milestone.",limitations:"Provider delivery dates are manually reported and require confirmation.",ruleVersion:"dependency-concentration-v1"},
    {id:"ins-core-budget",finding:"Core Platform Renewal is forecast 10.1% above its approved budget.",severity:"HIGH",confidence:"High · 90%",explanation:"Persisted programme forecast is GBP 17.4m against GBP 15.8m approved.",limitations:"Forecast excludes unapproved change requests.",ruleVersion:"investment-variance-v1"},
    {id:"ins-evidence",finding:"Payments Modernisation has lower evidence coverage than comparable active projects.",severity:"MEDIUM",confidence:"Medium · 78%",explanation:"Twelve authorised evidence records support the project versus a portfolio active-project median of twenty-two.",limitations:"Evidence quantity does not independently establish evidence quality.",ruleVersion:"evidence-coverage-v1"},
  ],
  investment:{authorized:true,currencies:["GBP"],aggregationAllowed:true,notice:"Development fixture values · GBP · reporting period August 2026 · refreshed 20 Aug 2026."},
};
